### ISSUE TITLE
Example without api-routes folder

### ISSUE THREAD

**Issue by lukiano** [kogosoftwarellc/open-api#107]
Hi, I'm looking for an example where the paths are defined in the .yaml file, instead of being in a folder, and the handlers are manually added later to Express. Thanks

**Comment by jsdevel** [comment]
Something like this? https://github.com/kogosoftwarellc/open-api/pull/88

**Comment by lukiano** [comment]
Not really, that one still has paths defined: `paths: path.resolve(__dirname, 'api-routes')`. I'm looking for an example that doesn't rely on scanning folders

**Comment by jsdevel** [comment]
Also see https://github.com/kogosoftwarellc/open-api/pull/60

**Comment by jsdevel** [comment]
See #60.  Feel free to reopen

**Comment by lukiano** [comment]
Thanks for #60. Then if I 

- manually parse the Swagger YAML (using js-yaml)
- retrieve all the paths and http methods for each path
- build the paths field for the arguments, an array whose entries have the structure {path, module} and having a dummy express handler on each defined http method in the module object

It results in express-openapi not requiring the paths to be valid folders and try to read express handler from files within those folders.

**Comment by lukiano** [comment]
Typescript:
```
const apidef = jsYaml.safeLoad(descriptor) as openapi.OpenApi.ApiDefinition;
        const paths = new Array<openapi.OpenApi.RouteSpecification>();
        if (apidef.paths) {
          for (const key of Object.keys(apidef.paths)) {
            const pathItemObject = apidef.paths[key];
            const module: openapi.PathModule = {};
            for (const method of Object.keys(pathItemObject) as Array<keyof openapi.OpenApi.PathItemObject>) {
              if (method !== '$ref' && method !== 'parameters') {
                module[method] = (_req, _res, next) => next();
              }
            }
            paths.push({
              path: key,
              module
            });
          }
        }
        openapi.initialize({
          app: this._router,
          apiDoc: apidef,
          exposeApiDocs: true,
          docsPath: '/api.html',
          paths
        });
```
