### ISSUE TITLE
errorMiddleware argument validation

### ISSUE THREAD

**Issue by fijshion** [kogosoftwarellc/open-api#108]
I spent too long trying to figure out why my errorMiddleware function wasn't being called. The problem was that I only defined three of the four args because next() isn't used. My linter has a rule to disallow unused function arguments which I think is fairly common. The requirement to define all 4 arguments on errorMiddleware should be relaxed or better documented.

See https://github.com/kogosoftwarellc/open-api/blob/c41f62b0fa20210456a8ae927e94a5d0f2972a2b/packages/express-openapi/index.js#L124

**Comment by jsdevel** [comment]
Thanks @fijshion.  I could see how that was confusing.  Can you open a PR to add that in the README?  This convention (i.e. error middleware with 4 arguments) originates from [express](https://expressjs.com/en/guide/error-handling.html)

**Comment by jsdevel** [comment]
closed by #109
