### ISSUE TITLE
Option to validate all responses

### ISSUE THREAD

**Issue by DaleJefferson** [kogosoftwarellc/open-api#11]
I can't find an option to validate all responses, it gets repetitive to keep doing.

```
const validationError = res.validateResponse(200, json);
if (validationError) {
    return next(validationError);
}

res.json(json);
```

**Comment by jsdevel** [comment]
Yea, I agree.  What would you suggest?

**Comment by jsdevel** [comment]
I usually add middleware to my stack that formats my data in a certain way.

So for example, I may call a service from my controller, and that service will give me most of what I need.  But usually in an API you have additional information you want to return.

Here's an example of what I may want to return from my API layer:

```javascript
{
  "statusCode": 200,
  "resource": {
    "name": "Tom Foolery"
  }
}
```

From my service layer though, I'm not concerned about status code, so my services would return this:

```javascript
{
  "name": "Tom Foolery"
}
```

My controller would then look like this:

```javascript
get: [addResourceResponseMiddleware, function(req, res) {
  myPersonService.getPerson(function(err, person) {
    res.sendAPIResource(200, person);
  });
}]
```

addResourceResponseMiddleware would look like this:

```javascript
function addResourceResponseMiddleware(statusCode, resource) {
  var proposedResponse = {
    statusCode: statusCode,
    resource: resource
  };
  const validationError = res.validateResponse(statusCode, proposedResponse);
  if (validationError) {
    return next(validationError);
  }

  res.status(statusCode).json(proposedResponse);
}
```

**Comment by DaleJefferson** [comment]
Personally I found this option confusing,

> x-express-openapi-disable-response-validation-middleware

I assumed that response validation was turned on i.e. all responses were validated and that option opted you out for a specific request.

This would be the simplest and then you could use x-express-openapi-disable-response-validation-middleware to opt out.
```
app.set('response-validation', true);
```

But maybe this is a better idea?

```
res.validateAndSendJSON(200, json);
```

**Comment by jsdevel** [comment]
> I assumed that response validation was turned on i.e. all responses were validated and that option opted you out for a specific request.

Yea, I can see that.  Perhaps that should be renamed to `x-express-openapi-add-validation-methods`?

**Comment by jsdevel** [comment]
> res.validateAndSendJSON(200, json);

I like this.  What would it look like for other content types like XML?

**Comment by jsdevel** [comment]
Almost seems like `res.validateAndSend` would be best, as the content type should be defined by your openapi document.

**Comment by DaleJefferson** [comment]
I've just added validateAndSendJSON to my project and it seems to work well.

```
app.use((req, res, next) => {
    res.validateAndSendJSON = (statusCode, json) => {
        const validationError = res.validateResponse(200, json);

        if (validationError) {
            return next(validationError);
        }

        res.status(statusCode).send(json);
    };
    next();
});
```

Is  x-express-openapi-disable-response-validation-middleware a performance optimisation? I'm not sure what harm it does having validateResponse available on every request.

**Comment by DaleJefferson** [comment]
Yes res.validateAndSend would be better

**Comment by jsdevel** [comment]
> Is x-express-openapi-disable-response-validation-middleware a performance optimisation? I'm not sure what harm it does having validateResponse available on every request.

It was mainly to prevent the method from colliding with other libs mainly.

**Comment by jsdevel** [comment]
If you can open a PR to add `res.validateAndSend` to this project that would be awesome.

**Comment by jsdevel** [comment]
Or should it be separate middleware?

**Comment by DaleJefferson** [comment]
Thanks for your prompt response @jsdevel a separate middleware that is loaded by default like the others?

I'm trying express-openapi on a small project, next I plan to use it on a large enterprise project. So far i'm really happy with this library.

**Comment by jsdevel** [comment]
> a separate middleware that is loaded by default like the others

Yea.  Perhaps this could go in `express-openapi-response-validation`?  Feels related to that an not necessarily something that `express-openapi` should manage.

> So far i'm really happy with this library.

I'm glad to hear it!

**Comment by DaleJefferson** [comment]
I will try to find some time to put a pull request together.

**Comment by jsdevel** [comment]
Sounds good!  What do you feel about making it in `express-openapi-response-validation`?  I feel it belongs there.

**Comment by DaleJefferson** [comment]
I agree, I will add it to express-openapi-response-validation, it should be pretty simple. The only bit i'm unsure about is how to handle XML.

What would this line look like for XML?

```
res.status(statusCode).send(json);
``` 

We would need to depend on a xml serialised and give options for formatting, I really would prefer to just do JSON.

Would you accept res.validateAndSendJSON and someone who is using XML can add res.validateAndSendXML and then validateAndSend can be created.

**Comment by jsdevel** [comment]
So I was researching this in the current schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json

Looks like you can define a `produces` array at the [apiDoc](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object) level and the [operation level](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object). 

I'd say the logic on our end would be this:

* If no `produces` array is defined in the api doc and the operation doc
  * use 'json`
* If a `produces` array exists...
  * and the only mime type listed is `application/json`
    * use `json`
  * and `application/json` is not in that list
    * use `send`
  * and mixes `application/json` with other mime types
    * use `send` and `console.warn` on startup.

**Comment by jsdevel** [comment]
@DaleJefferson I'm curious to know if you've made any progress on this.  I feel it would be a great addition.

**Comment by DaleJefferson** [comment]
I wrote my own wrapper that validates the response. I agree that this should be part of the project, I will try to find some time to add this.

**Comment by tjaartvdwalt** [comment]
any progress on this?

**Comment by jsdevel** [comment]
ping @DaleJefferson

**Comment by jcheroske** [comment]
I ran into this same issue and I just wanted to add my two cents.

First off, why does the code snippet above hardcode the "200" status code? How come it's not:
```
app.use((req, res, next) => {
    res.validateAndSendJSON = (statusCode, json) => {
        const validationError = res.validateResponse(statusCode, json); // <-- Why not pass the code in?

        if (validationError) {
            return next(validationError);
        }

        res.status(statusCode).send(json);
    };
    next();
});
```
This way, the schema will be consulted and the response that matches the code will be the one validated against. I made the above change and everything is working correctly.

Second, the use-case I'm hitting, and I'm assuming others have as well, is that the REST api needs to support different response formats, as specified by the client. A call might look like:
```
GET /v3/providers?format=xml
```
It would be great if the `validateResponse` method took in the format and then validated that it was in fact a valid format for that endpoint:
```
res.validateResponse(200, responseData, { format: 'xml' });
```
Maybe something like that?

**Comment by jsdevel** [comment]
> First off, why does the code snippet above hardcode the "200" status code?

I think the `200` was being passed in from the handler.  I don't believe it was hard coded in the middleware.

> It would be great if the validateResponse method took in the format and then validated that it was in fact a valid format for that endpoint:

I agree.  It should be fairly straightforward to check the operationDoc or apiDoc for produces.  If the provided data is of type Object and the operation can produce JSON, then it should use `.json`.  Otherwise it should probably just use `.send`.

**Comment by jcheroske** [comment]
Just to clarify, I see two separate needs in regards to the format/produces issue:

1) Verifying that the format being requested by the client is in fact produced by the endpoint. This is a simple fix, and pretty much just requires passing in the requested format (probably the MIME type) to the `validateResponse()` method. Perhaps:

  * No format requested / no produces -> Valid
  * No format requested / one produces -> Valid
  * No format requested / multiple produces, one of which is JSON -> Valid
  * JSON format requested / no produces -> Valid
  * X format requested / one or more produces, X among them -> Valid
  * Anything else -> Invalid

The important point here is that we are *not* making decisions about sending the data (`res.json()` or `res.send()`). We are just validating that the format the client is requesting is available. If the client doesn't request a format, then the most logical defaults are inferred.

2) Converting the outgoing data into the correct format. This is a harder problem because some formats require configuration before they can be used. XML may require the correct schema to be selected, and a suitable converter library, such as a CSV or XML generator might need to be plugged in.

If #1 is solved it makes solving #2 much easier. Maybe if a new method, `responseMimeType()` was added to the response object that would contain, after validation, the correct format of the response, then the `validateAndSend()` middleware could be rewritten like so:

```
const formatToMimeMap = {
  json: 'application/json',
  xml: 'application/xml',
  csv: 'text/csv'
};

app.use((req, res, next) => {
  res.validateAndSend = (statusCode, data) => {
    const mimeType = formatToMimeMap(req.query.format);  // client can request format or not
    const validationError = res.validateResponse(statusCode, data, { mimeType } );

    if (validationError) {
      return next(validationError);
    }

    res.status(statusCode);

    switch (res.responseMimeType()) { // new method that contains requested type or default
      case 'application/xml':
        // convert to xml and send it
        break;
      case 'text/csv':
        // convert to csv and send it
        break;
      default:
        res.json(data);
    }
  };
  next();
});
```

**Comment by Frizzled** [comment]
If you want to automatically validate responses with res.json() use this express middleware:

```
module.exports = function() {

    return async function(req, res, next) {
        let resJson = res.json;

        res.json = function() {
            let statusCode = res.statusCode || 200;
            let validationError = res.validateResponse(statusCode, arguments[0]);
            if (validationError) {
                console.error(validationError.errors);
                if (process.env.STRICT) {
                    return res.status(500).json('Unsupported implementation', validationError);
                }
            }
            resJson.apply(this, arguments);
        };

        next();
    };
};
```

**Comment by maxwellb** [comment]
I picked up express-openapi a few weeks ago, and my initial impression was the same as @DaleJefferson - the documentation described how to disable the feature, and I assumed for lack of other description that implied that validation was otherwise enabled and performing magic in the middleware.

For what it's worth, I'm observing a few implementations of what "automatic validation producing errors" would look like. I also would want options either to log and fail, or log and proceed. Perhaps an option to provide a middleware is best, during `initialize`.

If the option is undefined, proceed as normal, if the option is present, then before the response is sent, perform `res.validateResponse`, and if there is an error, run the configured middleware.

This would allow the current validateResponse middleware to exist unchanged, and provide a configuration point closer to openapi-express. That is, not requiring an independent middleware assume  a dependency on a properly configured openapi stack.

**Comment by jsdevel** [comment]
@maxwellb the problem with middleware is that your controllers will call a method like `res.json()` after validation has passed and no other middleware will get called, unless you're using koa.  With express you'd have to assign something to req (which is weird) or res (which is also weird) before calling next.  Is that what you were thinking?

**Comment by maxwellb** [comment]
@jsdevel No, and perhaps that limitation would be too significant. I was thinking something like:

```js
openapi.initialize({
    // ...,
    validationProcessorMiddleware: function DoValidation(req, res[, next]) {
        const err = res.validateResponse(res.statusCode, res.body);
        if (err) {
            res.status(500);
            logger.error(err);
            res.body = new Error(err);
            next();
            return;
        }
        next();
    }
});

```

Where in the above, I can choose whether the status and body are overwritten or not. What I get from your reply, is that either express doesn't have a direct way to modify (the concept of) `res.body` within a middleware function, or there is not a direct way to insert the middleware at the appropriate layer to do so.

Unfortunately, maybe that's a limitation of express itself, and would involve doing things like overriding `res.send`. Is that correct?

**Comment by jsdevel** [comment]
even with your suggested approach, how would you invoke that from an operation handler?  i think you'll see what i mean when you look at it from that perspective.

yea, @Frizzled 's approach in https://github.com/kogosoftwarellc/open-api/issues/11#issuecomment-405973426 is likely the best approach, but you can add it at the api level to avoid duplication.  See https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi#configuring-middleware

**Comment by maxwellb** [comment]
@jsdevel Yes, I think I can use `'x-express-openapi-additional-middleware': [myMiddleware]` to provide the function of overwriting `res.json`. Thank you for pointing me in that direction. Then it looks like operations can opt out of strict response validation by using `'x-express-openapi-inherit-additional-middleware': false`, so long as I don't want to keep potentially other middleware. Or, I can just check the type of `res.validateResponse` during "myMiddleware".

I suppose this would look like the following. Then "invoking from an operation handler" would process always, unless disabled. Though the remaining challenge is your earlier caution around possibly other code calling `res.json` or `res.send` out of the desired order.

```js
function responseValidationMiddleware(req, res, next) {
    // Introduce check of res.validateResponse to handle possible
    // case of "x-express-openapi-disable-response-validation-middleware": true
    if (typeof res.validateResponse === "function") {
        const resJson = res.json;
        res.json = function () {
            // call validateResponse
            // call original res.json with body or set error
        };
    }
    next();
}
// ...
'x-express-openapi-additional-middleware': [ responseValidationMiddleware ],
```

**Comment by maxwellb** [comment]
> I'm wondering if we can close this issue now, because I'm having a hard time thinking of an alternative that isn't too prescriptive. Perhaps this could be documented in openapi-response-validator's README? @maxwellb thoughts on submitting a PR to submit an example with your findings?

Submitted #311

**Comment by jsdevel** [comment]
with #311, i feel this can be closed.  if anyone has feelings to the contrary, please re-open.
