### ISSUE TITLE
Unable to load ts files routes with ts-node

### ISSUE THREAD

**Issue by Nox-404** [kogosoftwarellc/open-api#134]
Hello,
I got some trouble loading routes with `fs-routes` in `TypeScript`.
When using `express` and `express-openapi` with `ts-node`, I can't get any routes to load.
`ts-node` is dynamically loading `ts` files on-demand, but since `fs-routes` look for js files, it doesn't see anything.

Is there a way to make `fs-routes`to pick up those `ts` files, or to make `ts-node` pick them ?

**Comment by jsdevel** [comment]
> Is there a way to make fs-routesto pick up those ts files, or to make ts-node pick them ?

Yes, please submit a PR to allow those file extensions.  It probably needs to be an arg for express-openapi that gets passed to fs-routes.

**Comment by jsdevel** [comment]
@Nox-404 see #135.

**Comment by Nox-404** [comment]
Awesome, thx
