### ISSUE TITLE
Support for root path

### ISSUE THREAD

**Issue by srogers202** [kogosoftwarellc/open-api#137]
Hey Joe! Thank you for continuing to work on this... it's one of my favorite API frameworks to work with!

I'm developing some serverless APIs in Google Cloud, and there is always a relative base path. For example, in `{domain}/api1/v1/path/to/resource`, **/api1** is the root path, but I don't want to add it to `basePath`, or I'll get `/api1/api1/v1/...`. When I use petstore, all requests are made to `/v1/...`, without the `/api1` root.

Is there a way around this currently? If not, can I add a `rootPath` (or whatever we want to call it) field that will be inserted when generating the `basePath`? 

```
req.apiDoc.basePath = req.baseUrl + rootPath + basePath;
```

Thanks!

**Comment by jsdevel** [comment]
Glad it's useful for you!

I _think_ I understand what you're facing.  So google adds `api1` to the end of the endpoint?  And then your API paths are supposed to come after that?  I.e. `{domain}/api1` (managed by google) `/v1/path/to/resource` is added by `express-openapi`?

**Comment by jsdevel** [comment]
I _think_ this can actually be handled naturally with `req.baseUrl` https://github.com/kogosoftwarellc/open-api/blob/master/packages/express-openapi/index.js#L358

**Comment by jsdevel** [comment]
https://expressjs.com/en/api.html#req.baseUrl

**Comment by srogers202** [comment]
That’s perfect! I didn’t even notice the Host header. Thanks, Joe!
