### ISSUE TITLE
Fix link in main README

### ISSUE THREAD

**Issue by BBKolton** [kogosoftwarellc/open-api#138]
Don't have the opportunity to change it myself, but the link for `It is also possible to have just one central apiDoc.` is 404'd. Use https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi/test/sample-projects/basic-usage-with-central-apiDoc instead

**Comment by jsdevel** [comment]
Thanks!  Published in `express-openapi@1.10.1`
