### ISSUE TITLE
Typescrript: Unable to pass cb(null, true) on successfull auth

### ISSUE THREAD

**Issue by gnuton** [kogosoftwarellc/open-api#139]
Hi!
The documentation says I should be able to call the  
cb(null, true) in case auth is successfull, but the d.ts file doesn't allow that in TS code.

Could you please make the error type nullable in here: https://github.com/kogosoftwarellc/open-api/blame/master/packages/express-openapi/index.d.ts#L119

Something like this should work
export interface SecurityHandlerCallback {
    (error: SecurityHandlerError | null, result: boolean): void;
}

Thanks

**Comment by gnuton** [comment]
Note for TS devs.
As for now we can get around this issue by casting null to any and keep strict null checks enabled.
cb(null as any, true)

**Comment by jsdevel** [comment]
Thanks!  Published in `express-openapi@1.10.1`
