### ISSUE TITLE
host and basePath are invalid in OpenAPI 3.0

### ISSUE THREAD

**Issue by fluggo** [kogosoftwarellc/open-api#142]
https://github.com/kogosoftwarellc/open-api/blob/b1745633b13aff9d0c284312eac0881cdbc70063/packages/express-openapi/index.js#L357-L358

The `host` and `basePath` attributes don't pass validation in OpenAPI 3.0, at least according to the Swagger UI. These look like they've been replaced by the [`servers`](https://swagger.io/docs/specification/api-host-and-base-path/) attribute.

**Comment by jsdevel** [comment]
thanks @fluggo !  published a fix in `1.10.2`.

**Comment by fluggo** [comment]
Thank you!
