### ISSUE TITLE
Option Argument 'args.routesIndexFileRegExp' is required in d.ts

### ISSUE THREAD

**Issue by YannickMeeus** [kogosoftwarellc/open-api#145]
Hiya, I've just updated from a relatively old version to latest, and I'm getting some Typescript build failures around `args.routesIndexFileRegExp` being a required field, and when having a look at the d.ts file, this is indeed a thing:

```
...
 pathsIgnore?: RegExp
    routesGlob?: string;
    routesIndexFileRegExp: RegExp; //<-- Not optional
    docsPath?: string
    errorMiddleware?: express.ErrorRequestHandler,
...
```
The README, however, is saying this is not required. I can get around this by just setting it to the default value for the time being but just wanted to let you know the documentation is at odds with the d.ts. file.

**Comment by jsdevel** [comment]
Thanks!  Just pushed a fix.  I'll publish shortly
