### ISSUE TITLE
Design of OpenAPIRequestValidator

### ISSUE THREAD

**Issue by LandonSchropp** [kogosoftwarellc/open-api#146]
Thank you all for tackling this problem!

Our team is attempting to use the `openapi-request-validator` package to write a custom Koa middleware. We know you guys have a Koa middleware planned, but we figured we'd write a simplified version. We'd be happy to contribute to a larger middleware, and we're okay with maintaining our own if our visions are incompatible.

We're currently finding the interface to `OpenAPIRequestValidtor` a little hard to understand. To us, ideally the process would look something like this:

```
new OpenapiRequestValidator(openapiSchema).validate(request)
```

Where `openapiSchema` is our full Open API JSON object and `request` is a standardized request format. This would make writing a middleware trivial. Here's a simplified example:

```
export default async function validationMiddleware(context, next) {
  let openAPIDocument = parseOpenAPI(OPEN_API_PATH);

  let request = convertKoaRequestToOpenAPIRequest(context.request);
  let requestValidationResult = new OpenAPIRequestValidator(openAPIDocument).validate(request);

  if (requestValidationResult) {
    throw new ValidationError(requestValidationResult.errors[0].message);
  }

  await next();
}
```

We're struggling to understand the current `OpenAPIRequestValidator` API. It seems like we need to transform the Open API schema into some other format, but we're not sure what that format is or what it should look like. We looked at the implementation of the [Express middleware](https://github.com/kogosoftwarellc/open-api/blob/master/packages/express-openapi/index.js) for inspiration, but it's very daunting. 

We'd really appreciate some guidance on the best path forward. Ideally, the interface to the validator would match what we expect, but we're happy to take a different path if that is what is best moving forward. We might also be missing something in our understanding, and we would appreciate clarification if that's the case.

Thanks!

CC @griesmnr and @jorge0136

**Comment by jsdevel** [comment]
@LandonSchropp thanks for opening this issue.

`openapi-request-validator` was designed to handle the full range of things you can do with `jsonschema`, namely custom formats, extended schemas and so forth.

Your proposal isn't very far off from what `openapi-request-validator` _already does_ i.e.  you've proposed the following interface:

```
new OpenapiRequestValidator(openapiSchema).validate(request)
```

This is `openapi-request-validator`'s interface:

```
new OpenapiRequestValidator(options).validate(request)
```

The key difference here is that the full schema isn't needed to validate the request.  What's needed are the parameter definitions, the schema definitions, and the version of openapi used i.e. schema.definitions is added to `options.schemas`.

`openapi-request-validator` used to be express middleware, but I've been actively working on pulling parts out of `express-openapi` and making them generic: `openapi-request-validator` is a direct result of that effort and was built with a common request interface in mind i.e.

```
{
  body: ...
  query: ...
  params: ...
  ...
}
```

For koa, i was thinking that it'd be as simple as it is in express, and I wasn't even planning on publishing a separate package for the request validation.  Here's how it's currently wired into `express-openapi`:

```
var OpenapiRequestValidator = require('openapi-request-validator');
...
            var requestValidator = new OpenapiRequestValidator({
              errorTransformer: errorTransformer,
              parameters: methodParameters,
              schemas: apiDoc.definitions,
              externalSchemas: externalSchemas,
              customFormats: customFormats
            });
            middleware.unshift(function(req, res, next) {
              next(requestValidator.validate(req));
            });
...
```

I was thinking the koa implementation would look like this:

```
var OpenapiRequestValidator = require('openapi-request-validator');
...
            var requestValidator = new OpenapiRequestValidator({
              errorTransformer: errorTransformer,
              parameters: methodParameters,
              schemas: apiDoc.definitions,
              externalSchemas: externalSchemas,
              customFormats: customFormats
            });
            middleware.unshift(function(ctx, next) {
              next(requestValidator.validate(ctx.req));
            });
...
```

Let me know if you still have questions, and I'm thankful for your support!

**Comment by LandonSchropp** [comment]
@jsdevel Thanks for the awesome, detailed reply!

The reasoning behind the interface makes total sense, and it's kind of cool that you can validate more than what Open API supports. We did end up taking an approach very similar to the Express code you posted above.

One issue we ran into was matching requests (specifically requests with path parameters) with their appropriate configuration values. In particular, we had to build a custom regular expression that could match the current request with the correct schema. That code is [here](https://github.com/optimumenergyco/koa-utilities/blob/0b1beaebe53ecdbdb0eebc3a9d153eeec48977bf/lib/open-api.js#L44-L111).

This works, but my worry is that we missed something. One of the advantages to the interface I posted is that OpenAPIRequestValidator could match the request for us, eliminating this need. Is there a better way to accomplish this, or did we do the right thing?

**Comment by griesmnr** [comment]
@jsdevel Thank you for the help understanding the interface! What a relief it's been to have these repos to use on our koa apps.

We have built a simplified koa middleware to use on our projects. Its a first pass tailored to our projects and may not include all use cases, but we'd be happy to contribute what we have, or otherwise work with you on it! It'd be the least we could do. Hit me up if you're interested, at any point!

**Comment by jsdevel** [comment]
I'm glad you guys were able to find a workaround!  I'm in the process of getting `koa-openapi` going, so when that's ready I may draw your attention to that for review.  Going to close this now.  Thanks for your support!

**Comment by jsdevel** [comment]
FYI, `koa-openapi` is now ready.
