### ISSUE TITLE
OpenAPI security Handler doesn't allow errors to be formatted in different ways

### ISSUE THREAD

**Issue by gnuton** [kogosoftwarellc/open-api#150]
Hi,
OpenAPI security handler returns erros always as text eg: "Challenge is a required header with 401 status codes."
Would it be possible to get errors as JSON?

I would like to return errors for instance in Problem JSON format
So they would look like this:
header: 'content-type'/ 'application/problem+json'
body: {"type":"https://httpstatuses.com/401","title":"the_message","status":401}

Is it already possible to achieve this? If so how?

The code which create those error msgs is here:
https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-security-handler/index.js

**Comment by jsdevel** [comment]
Thanks for opening this.  Yes, this currently is a limitation.  I'm open to solutions.

**Comment by gnuton** [comment]
Well the best solution I guess would be to let  errors be handled by my
error-handling middleware function instead to be intercepted by the lib.
