### ISSUE TITLE
Support OpenApi 3.0 requestBody

### ISSUE THREAD

**Issue by seeker89** [kogosoftwarellc/open-api#162]
Hi and thanks for this package !

I've noticed, that https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-request-validator doesn't yet support `requestBody`, so if provided with OpenApi 3.0 spec, things mostly work, apart from validating the actual body.

Are there plans to add support for that ?

Thanks !

**Comment by jsdevel** [comment]
Right now I'm looking for the community to provide support for OpenAPI v3.  If you have the time to open a PR to add that functionality, it would be very much appreciated.

**Comment by seeker89** [comment]
Gotcha. Thanks for your answer.

**Comment by jsdevel** [comment]
closed by @bill-kitsune in #272!
