### ISSUE TITLE
Improve the response validation error for easier debugging

### ISSUE THREAD

**Issue by seeker89** [kogosoftwarellc/open-api#183]
Currently, the response validation errors look something like this:

```js
{
  errorCode: "enum.openapi.responseValidation"
  message : "response[194].fieldF is not one of enum values: A,B,C"
  path: "response[194].fieldF"
}
```

And that's great, thanks for writing this awesome library 👍 

What would be super amazing, though, is if the error included also the offending value, so that you can just read that log line, and understand what happened, instead of having to match it with some other log line containing the input.

If the concern is the potentially large size of a string representation, maybe even the first 10 characters of it would be helpful in a large chunk of cases.

What do you think ?

**Comment by jsdevel** [comment]
I agree it would be helpful.  May have to investigate to see how feasible it is if ajp doesn't provide that.

**Comment by jsdevel** [comment]
Actually, there could be issues where you _wouldn't_ want to log what the offending value was (like in the case of submitting credit card information).  If you can find some sensible settings for AJV please submit a PR.
