### ISSUE TITLE
README.MD usage is incorrect about how to specify openapi version

### ISSUE THREAD

**Issue by vkoldus** [kogosoftwarellc/open-api#189]
Readme states that the validate function accepts a second argument that specifies the version. However, it's actually expected to be part of the validator constructor function args object. The validate function only expects one argument.

I wanted to send you a pull request, but I couldn't push to your repo. I'm attaching a patch instead.
[patch.diff.zip](https://github.com/kogosoftwarellc/open-api/files/2374570/patch.diff.zip)

**Comment by jsdevel** [comment]
@vkoldus can you fork this repo and open a PR?
