### ISSUE TITLE
Can't get security handler to return a 401 without a "challenge" attributes

### ISSUE THREAD

**Issue by notxt** [kogosoftwarellc/open-api#197]
**Context:**
Looking to return `401`s when a token is missing from a header. Front end redirects to login if this is the case

**Issue:**
The docs indicate that you can use [`cb(null, false)`](https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-security-handler#response) from all securityHandlers to return a `401`. I only have one but I'm getting a `500` with:
```
No security handlers returned an acceptable response: token
```

**Notes:**
Looking at the code, it seems that without [`lastError.status`](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-security-handler/index.js#L99) defined there's no way to return a `401`

Also, when running `cb(null, false)` it seems the `lastError` becomes the first argument. So with `null` it would jump [`if (lastError)`](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-security-handler/index.js#L94) and it [the default `cb` block](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-security-handler/index.js#L135)

I'd be down to put in a PR, but I'm curious about you'd like the code to behave

Love your library! :two_hearts:

**Comment by jsdevel** [comment]
honestly, i think the way it was implemented was a little wonky.  how do you propose it should behave?

> Love your library! 💕

Thanks for supporting it!

**Comment by notxt** [comment]
Hm, I might need to google a bit on 401s and challenges before knowing exactly ... I can do that this evening

@buckwheat24 did you have any thoughts?

**Comment by jsdevel** [comment]
i'm thinking the handlers should change as follows:

* if they throw an error, the error is passed to the framework i.e. for express it would simply pass the error thrown to `next`
* if any of the handlers return `true` no error is thrown
* if none of the handlers return `true`, the security handler throws an error with `status=401` and the framework handles the error accordingly i.e. for express it would be passed to `next`

thoughts @notxt ?

**Comment by notxt** [comment]
same as above but with async support
```
function factory({handlerList, AuthError = Error}) {
  return async (req, res, next) => {
    let status;
    try {
      status = await Promise.all(handlerList.reduce(
        async (status, handle) => status || await handle(req),
        false
      ));
    } catch (e) {
      return next(e);
    }

    if (!status) {
      throw new AuthError({ status: 401 });
    }

    next();
  }
}
```

**Comment by notxt** [comment]
so the general business logic is:
- if *any* handler succeeds: authenticate
- if *no* handler succeeds: return `401`
- if *any* handler throws an error: next(err)

I like that because if you want a specific response you can throw and then write a [custom error handler](the-default-error-handler)

**Comment by jsdevel** [comment]
exactly!

**Comment by jsdevel** [comment]
i just think there are too many scenarios where the current API is too rigid (libraries should never call methods like `.json` imo).

**Comment by notxt** [comment]
Thanks! Can't wait to try it out!

**Comment by jsdevel** [comment]
i may have closed this a bit soon.  still need to publish `openapi-framework` and `express-openapi` with the latest version of `openapi-security-handler`.

**Comment by raplemie** [comment]
Am I missing something or the new openapi-security-handler (2.0.3) does not have examples that "connects" with other uses ? I see we can now create an object that has a "handle" promise, but where/how do I inject that into my apiDoc ? The example on the express-openapi still present the solution where everything is build directly in the apiDoc, thus no use for the openapi-security-handler.

I'm pretty sure I missed something obvious...

**Comment by jsdevel** [comment]
@raplemie see https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi#argssecurityhandlers.

Also look at the sample projects in the test suite.  This one has an example: https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi/test/sample-projects/with-securityHandlers

**Comment by raplemie** [comment]
So the information presented here: https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-security-handler is mainly for internal use by the library ? If we use express-openapi, the only difference is that we must define handlers with the return true/false/"throw" behavior instead of the callbacks?

I think that is what drove me on the wrong track, I thought that now I was supposed to instantiate a `const handler = new OpenAPISecurityHandler({...});` and use that somewhere, but I couldn't figure out where.

Thanks for that quick reply!
Raphael
