### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by allanchau** [kogosoftwarellc/open-api#198]
Hi,

Is there a changelog I can view somewhere?

**Comment by jsdevel** [comment]
<o o>
    ~

... no.  but there should be!  I'm thinking there should probably be one in each package as this _is_ a monorepo.

The closest thing right now is via git history.

**Comment by allanchau** [comment]
Thanks, no problem.

**Comment by jsdevel** [comment]
Thanks for raising this!  All future changes will be documented as follows: https://github.com/kogosoftwarellc/open-api/pull/208.
