### ISSUE TITLE
Question: Setting value to Null via OpenAPI

### ISSUE THREAD

**Issue by notxt** [kogosoftwarellc/open-api#213]
Hey! It's me again!

Just a quick question more related to OpenAPI than your implementation. I noticed that [`null` is not a valid type](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types)

How do you deal with attributes that can be set to `null` on update? Are they just omitted and then the code assumes that any non-required, omitted attribute should be set to `null`?

That seems like a workable solution but I was wondering if you knew of a better one

thanks!
michael

**Comment by jsdevel** [comment]
@notxt something like this? https://github.com/kogosoftwarellc/open-api/blob/master/packages/express-openapi/test/sample-projects/with-schema-extension/api-doc.js#L38

**Comment by notxt** [comment]
gracias sir!

**Comment by jsdevel** [comment]
@notxt can this be closed out?

**Comment by notxt** [comment]
@jsdevel absolutely, do you prefer when the reporter closes?

**Comment by jsdevel** [comment]
> do you prefer when the reporter closes?

i do, only because i want to be sure the issue was resolved properly.
