### ISSUE TITLE
seems "nullable" is not understood by validator

### ISSUE THREAD

**Issue by funduck** [kogosoftwarellc/open-api#218]
trying to use for OpenAPI3, validator wont understand  
```
"responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
```
So I have to bring "schema" up  
```
oav = require('openapi-response-validator')
v = new oav.default({
    summary: "Sum",
    description: "Desc",
    parameters: [],
    responses: {
        "200": {
            description: "Ok",
            schema: {
                "type": "object",
                "properties": {
                    "msisdn": {
                        "type": "string"
                    },
                    "countryId": {
                        "type": "string",
                        "nullable": true
                    }
                },
                "required": [
                    "msisdn"
                ]
            }
        }
    }
})

console.log(JSON.stringify(v.validateResponse('200', {"msisdn":"790000000000","countryId":null}), null, '  '))
```
output  
```
{
  "message": "The response was not valid.",
  "errors": [
    {
      "path": "countryId",
      "errorCode": "type.openapi.responseValidation",
      "message": "countryId should be string"
    }
  ]
}
```

**Comment by jsdevel** [comment]
@funduck if you have time, it would be appreciated if you'd open a PR with a test case in https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-response-validator/test/data-driven that reproduces this.

**Comment by funduck** [comment]
should I also add case for OpenAPI3 format? of response like  
```
"responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
```

**Comment by jsdevel** [comment]
yes please @funduck !

**Comment by jsdevel** [comment]
Man, really sucks that OAI decided to deviate from json schema :sigh:.  The response validator now needs to convert nullable to oneOf with type null.

**Comment by funduck** [comment]
Or result from ajv should be processed so that errors on "nullable" fields would be ignored and removed from response

**Comment by mbsimonovic** [comment]
validator doesn't undestand openapi v3, so what are my options then? to manually construct a config based on apidoc, disable the built-in middleware, and mount my own custom one?

**Comment by funduck** [comment]
just fixed it, will push to my fork soon. Just did what @jsdevel  proposed

**Comment by jsdevel** [comment]
thanks for closing @funduck !

**Comment by chadxz** [comment]
@jsdevel do you know if anything was ever pulled into the response validator to deal with nullable?
