### ISSUE TITLE
Coercion Strategy - Object type

### ISSUE THREAD

**Issue by nunodamaso** [kogosoftwarellc/open-api#232]
Will the type: "Object" be supported?

**Comment by jsdevel** [comment]
If there's a proposal with clear heuristics then yes.  Up until now there hasn't been any.

**Comment by nunodamaso** [comment]
Hi, I was thinking something along the following lines, regarding the Headers, Params, Query and FormData types:

{
...
type: object // or {}
} --> defaults to JSON.parse

{
...
type: object // or {}
format: json
} --> JSON.parse

{
...
type: object // or {}
format: Possible future implemented strategies(qs maybe?)
} -->strategy

{
...
type: array
items:
  type: object // or {}
  format: json
} --> JSON.parse

It should follow the same behaviour as the rest of the coercion strategies and return false when unable to parse.

It is also complient with the spec: "(...) Primitives have an optional modifier property: format. OAS uses several known formats to define in fine detail the data type being used. However, to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. Types that are not accompanied by a format property follow the type definition in the JSON Schema. Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified."

**Comment by jsdevel** [comment]
@nundamaso I like it.  Can you open a PR?

**Comment by nunodamaso** [comment]
Will do

**Comment by jsdevel** [comment]
closed by #234

**Comment by jsdevel** [comment]
@nunodamaso @Amxd: `express-openapi` and `koa-openapi` have been published with `args.enableObjectCoercion`.

**Comment by Amxd** [comment]
Perfect :) we're glad we could contribute :)
