### ISSUE TITLE
Publish openapi-3.0.json on schemastore

### ISSUE THREAD

**Issue by jabby** [kogosoftwarellc/open-api#238]
Hello maintainers, 

I start to write some open-api-3.0 documentation for my APIs and I discovered that this repository contains a really useful schema here. https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-schema-validator/resources/openapi-3.0.json

Do you think it's possible to publish it on http://schemastore.org/json/ ?

If you agree I can create the PR to the corresponding project in github. I just want to be sure you agree with this proposal first. 

Thanks for your answer. 
Have a nice day.

**Comment by jsdevel** [comment]
The one bundled in this repo is a bit of a stop gap until the official schema is published.  See https://github.com/OAI/OpenAPI-Specification/issues/1032.

You're free to do as you wish; however, we're not likely to reference it in any of our documentation until the official schema is published.

**Comment by jabby** [comment]
As you can see I created a PR on schemastore and link your schema. I will update the schema with the official one when it will be available.

**Comment by jsdevel** [comment]
Thanks for your support!
