### ISSUE TITLE
Type definitions do not match with the "Using Typescript" example

### ISSUE THREAD

**Issue by user-0209** [kogosoftwarellc/open-api#241]
The index.d.ts file that gets installed with express-openapi does not export a member "Operation". However, that is needed in the second part of the "Using with Typescript" example, where it imports like: 
import {Operation} from "express-openapi";

There is another @types/express-openapi module that does export "Operation". I'm confused about which type definition is right.

**Comment by jsdevel** [comment]
thanks!  published in `3.0.3`
