### ISSUE TITLE
Validation on multiple examples

### ISSUE THREAD

**Issue by tancredi** [kogosoftwarellc/open-api#264]
#### Problem

Multiple response examples don't seem to pass validation when running `swagger-cli validate [...]`

#### Example

Following the [specification provided in the docs](https://swagger.io/docs/specification/adding-examples/) I have the following examples in the spec of an endpoint response:

![screen-01](https://user-images.githubusercontent.com/1300753/48917639-c3522d00-ee7f-11e8-9541-0aa861fc2e58.png)

And the validation fails as follows:

<img width="824" alt="screen-02" src="https://user-images.githubusercontent.com/1300753/48917652-da911a80-ee7f-11e8-97c2-38b2b0575a8a.png">

#### Solution?

I've tried to move it around in different ways but I'm pretty sure there' an issue with the [JSON schema for this](https://github.com/kogosoftwarellc/open-api/blob/f552e7ae78837c327990729ee2f3b8ef727e0466/packages/openapi-schema-validator/resources/openapi-3.0.json#L1125)

Unfortunately I don't have much expertise when it comes to JSON schemas, so sorry I'm not coming to this with a PR, maybe someone with a bit more knowledge of the codebase can have a look. 

Thanks

**Comment by jsdevel** [comment]
Can you provide the API doc that fails validation?

**Comment by tancredi** [comment]
Hi @jsdevel , While I cannot provide the original full spec, I've created an example repo from which you can reproduce this:
https://github.com/tancredi/swagger-examples-validation-demo

**Comment by tancredi** [comment]
Is that helpful? Happy to provide more context if needed

**Comment by jsdevel** [comment]
it's helpful.  sorry, getting over the Thanksgiving holiday here in the states.  i suspect that this issue has to do with the schema in openapi-types.  can you see if you can add a test case to that package and run it's tests?

**Comment by jsdevel** [comment]
looking at the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#external-documentation-object), it looks like `example` allows `any`.  If you use examples, you're limited to using an [ExampleObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject) or a [ReferenceObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#referenceObject).  [openapi-types](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-types/index.ts#L200) appears to define these correctly, so I'm assuming it's an issue with your schema.

**Comment by tancredi** [comment]
I can imagine - thanks for the fast response though - seems I was just being thick - didn't realise I had to put the example data under `value` - thanks for helping out!
