### ISSUE TITLE
rfc: wildcard or regex for variable path lengths

### ISSUE THREAD

**Issue by mbsimonovic** [kogosoftwarellc/open-api#265]
I have a similar use case like (OpenAPI-Specification/issues/892)[https://github.com/OAI/OpenAPI-Specification/issues/892] - a single path that should accept for example all of these:
 
 * `/api/tags/`
 * `/api/tags/foo`
 * `/api/tags/foo/bar/baz`
 
It would be great to define this as `/tags/{/variablePath*}`. This would be trivial with express router: `app.use('/api/tags/*', tagsRouter);`, but seems like OpenAPI doesn't support it and might never. Anyone knows a workaround?

**Comment by mbsimonovic** [comment]
found one: 
```
 paths: [
        { path: '/tags/*', module: require('./api-v1/paths/tags.js') }
]
```
but the spec is still not correct.

**Comment by jsdevel** [comment]
@mbsimonovic thank you for supporting this package with your idea!

it's a cool feature request, but this project is aimed at supporting the OpenAPI spec as closely as possible.  It goes beyond having express (or another frameworks') router exposing the routes properly, it also has to do with outputting an OpenAPI compliant document that can be understood by client SDKs and OpenAPI compliant UIs.

Going to close this, but if you have a proposal that will result in an OpenAPI compliant document, then please feel free to re-open.
