### ISSUE TITLE
Thoughts on using a linter/formatter for this project? 

### ISSUE THREAD

**Issue by bill-kitsune** [kogosoftwarellc/open-api#273]
I was working on a PR and noticed a lot of the code was written with a certain style, that I found tedious to try to match.  

Would the maintainers be interested in or have any plans to add a linter to the project? Prettier, or even just tslint?

**Comment by jsdevel** [comment]
> Would the maintainers be interested in or have any plans to add a linter to the project?

yes!

> Prettier, or even just tslint?

both are fine, but no git hooks please

**Comment by jsdevel** [comment]
beautifully closed by #275!  thanks again @bill-kitsune !
