### ISSUE TITLE
Support for servers attribute for OpenAPI 3.0

### ISSUE THREAD

**Issue by bill-kitsune** [kogosoftwarellc/open-api#274]
2.0 uses a basePath attribute that the library uses to modify the paths that are created.  3.0 uses the servers attribute which is a list of servers.

Initial thoughts on how this could work is something like the following:

Add a useServer argument to `OpenAPIFrameworkArgs` interface. 

The arg could have the following behavior:

* Is optional
* Only matters if the apiDoc is a OpenAPI 3.x.x document
* If not set the framework will use the first servers path for basePath
* If set the framework will match the argument to the server description
* If set and cannot match on server description throw error (thoughts on this?)

This would allow people to do the following:

```
expressOpenApi.initialize({
      apiDoc,
      app: this.express,
      dependencies: {
        worldsService: WorldsService,
      },
      paths: path.join(__dirname, './api/v1/paths'),
      useServer: process.env.NODE_ENV || 'development'
    })
```

Thoughts?

**Comment by jsdevel** [comment]
does the spec provide guidance on a default server in the list?  or is that up to implementations to decide?  overall i feel the heuristics you've outlined herein are sound and would welcome a PR to implement this!

**Comment by bill-kitsune** [comment]
So doing a bunch of reading on this this morning.  It seems that overall intent is something like "The important thing is that OpenAPI description for all the servers is the same."

It allows for things like this: 

```
"servers": [
    {
      "url": '/foo'
    },
    {
      "url": '/bar'
    },
    {
      "url": "http://{host}/api",
      "description": "Public Servers",
      "variables": {
        "enum": ["test.foo.com", "foo.com"]
        "host": {
          default: "test.foo.com"
        }
      }
    },
    {
      "url": /{why},
      "variables": {
         "why": {
            "default": "to-watch-the-world-burn"
         }
       }
    }
  ],
```
So this would mean that the api can be found can be found at any of these locations.  I don't think that in normal use cases people would have such diverse server definitions, but it's possible I guess.

So to that end I think I will adjust my original idea to something along the lines of:

* No need for any additional arguments
* Should create routes at all defined paths described by the servers list.
* For express convert path params to express path params (I assume similar will have to be done for the other frameworks supported, but I am less familiar with them)
* If there are enums we can build a regex to validate them like `/:myVar((enum1|enum2))`

The only thing I'm kind of on the fence about is how to handle that host param example.  What if you spin the api up at a different host.  Should it still include the /api base route? Should there be some check added that says unless the host name matches the enum I will 404? Am I overthinking this a bit? Have I lost my mind after reading the OA spec and issues all morning... maybe... 

I will try to put together a PR for this though, as I have some time this week.

**Comment by jsdevel** [comment]
> Have I lost my mind after reading the OA spec and issues all morning... maybe...

i think we're all in that category :stuck_out_tongue:

**Comment by bill-kitsune** [comment]
@jsdevel Question on how to handle this issue with regards to the multiple projects within this repo.  A lot of things depend on `openapi-framework`.  Once that supports servers, should separate issues be created for things like  `express-openapi` and the like to then take advantage of that? 

I guess I also ask because `express-openapi`depends on the version of `openapi-framework` it gets from  npm.  So we would also need to wait for a publish before moving forward?

**Comment by jsdevel** [comment]
@bill-kitsune I can publish fairly quickly.  You're right on about openapi-framework.  The update likely needs to go there.  For local development until it's published you can npm link from the packages.
