### ISSUE TITLE
"header" instead of "headers"

### ISSUE THREAD

**Issue by AlexHolly** [kogosoftwarellc/open-api#310]
The result is called "headers" but OpenAPI uses "header". Would be nice to keep things consistent.
Current
```
   headers: {
     properties: {
       Accept: {
         type: 'string'
       }
     }
   },
```
Expected
```
   header: {
     properties: {
       Accept: {
         type: 'string'
       }
     }
   },
```
https://github.com/kogosoftwarellc/open-api/blob/360af7345f18399c7998fb8d99ca5f5e9893f295/packages/openapi-jsonschema-parameters/index.ts#L6
https://github.com/kogosoftwarellc/open-api/blob/360af7345f18399c7998fb8d99ca5f5e9893f295/packages/openapi-jsonschema-parameters/index.ts#L30

**Comment by jsdevel** [comment]
not sure how i feel about this one, because the resulting object isn't one defined by OpenAPI, and is used more internally.

**Comment by jsdevel** [comment]
going to close this, as it's not really deviating from the spec.
