### ISSUE TITLE
Invalid GitHub link on openapi-response-validator

### ISSUE THREAD

**Issue by AlexHolly** [kogosoftwarellc/open-api#316]
1. https://www.npmjs.com/package/openapi-response-validator
https://github.com/kogosoftwarellc/open-api/tree/master/packages/eopenapi-response-validator

2. The example has a small typo it should be "OpenAPIResponseValidator" not "OpenapiResponseValidator"

```
var OpenapiResponseValidator = require('openapi-response-validator');
var instance = new OpenapiResponseValidator({
```

**Comment by jsdevel** [comment]
thanks!  can you open a PR?
