### ISSUE TITLE
Unable to create Object missing constructor

### ISSUE THREAD

**Issue by AlexHolly** [kogosoftwarellc/open-api#317]
I am not able to create an object "constructor not found"
As a workaround I had to add `module.exports = OpenAPIRequestValidator`
same for the response validator

```
var OpenAPIRequestValidator = require('openapi-request-validator')
var instance = new OpenAPIRequestValidator({...})
```

Am I doing something wrong?
using  "node": "10.11.0"

**Comment by jsdevel** [comment]
we're transpiling to es6, so try `require('openapi-request-validator').default`
