### ISSUE TITLE
Is there a way to just provide operation handlers?

### ISSUE THREAD

**Issue by sebasmagri** [kogosoftwarellc/open-api#336]
I'd like to have an apiDoc which provides `paths`, and then just pass in a module which could have all the operations defined using the same `operationId`, and the dependency handling.

This makes it much easier to maintain the api and publish docs for my use case, and allows me to use other tools that consume the apiDoc.

Is there a supported way to do this? If not, any pointers to implement something like this?

**Comment by jsdevel** [comment]
Checkout the openapi-framework package.  It'll scan your directory door operation handlers and let you wire it up manually.  It's that what you mean?

**Comment by jsdevel** [comment]
@sebasmagri i think what you're asking for would be a great feature.  just so i understand, i think what you want is to have this framework do nothing but parse your existing api doc and add middleware etc. according to that?  meaning, this framework wouldn't try to gather your api doc together, it would only respond to it?

i feel that would be a welcomed addition.

**Comment by sebasmagri** [comment]
@jsdevel exactly, the scenario would be to generate, using express for example, an express application out of an api doc, by providing only the api doc plus a module or object with functions which names match the `operationId`s defined in the api doc.

I'm currently using something like this to partially implement this approach, still without middlewares:

```
  for (let [path, spec] of Object.entries<PathsObject>(apiDoc.paths)) {
    for (let method of methods) {
      if (spec[method]) {
        let operationId = spec[method].operationId;
        if (operationId) {
          let controller = apiControllers[operationId];
          if (apiControllers[operationId]) {
            apiApp.use(path, controller(services));
          } else {
            this.logger.warn('controller not found', { path, method, operationId });
          }
        } else {
          this.logger.warn('path method without operationId', { path, method });
        }
      }
    }
  }

```

**Comment by jsdevel** [comment]
i think if you were to pass in an `operations` arg to `.initialize`, you could easily match up the operation handler to the path and then let it function as it normally does.  we've actually been wanting to do this for a while since we'd be able to add support for typescript decorators see #42

**Comment by sebasmagri** [comment]
That was the first thing I wondered, but then seeing `paths` being mandatory scared me a bit of that approach being too much work.

**Comment by jsdevel** [comment]
@sebasmagri i added experimental support for `args.operations`.  You can pass in an object of `operationId` to `function` e.g.:

```
.initialize({
  operations: {
    getFoo: function(req, res, next) {
      res.send('foo');
    }
  }
})
```

**Comment by sebasmagri** [comment]
@jsdevel that's awesome! I was planning to work on this a bit this weekend. I'm gonna try that out in the next few days and let you know how it goes.

**Comment by jsdevel** [comment]
Got it working!

See:
https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi#argsoperations
https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi/test/sample-projects/basic-usage-with-central-apiDoc

P.S. I feel this is leading us towards decorators! https://github.com/kogosoftwarellc/open-api/issues/42

**Comment by sebasmagri** [comment]
@jsdevel just tried it and its working pretty good. The only thing I miss still is a way for the operations to get `dependencies` injected. I guess that's only supported when using `paths`? How could I achieve this or help getting this supported?

**Comment by jsdevel** [comment]
@sebasmagri this is where decorators could come into play!  The issue with the current approach to operations is that the framework has no way of knowing if the function is a handler or if it should be injectable.  Something like an `@Inject` decorator could assign a property to the function to let the framework know it should inject dependencies.

**Comment by sebasmagri** [comment]
@jsdevel right, I checked it out and I think we could get something going by setting `module` instead on each route when populating from the operations argument. What do you think?

**Comment by jsdevel** [comment]
@sebasmagri the framework still has no way of knowing if the function should be injected or is a handler

**Comment by sebasmagri** [comment]
@jsdevel you're right, I was considering it should always inject, so that operations should always return the handler function
