### ISSUE TITLE
Passport.js integration

### ISSUE THREAD

**Issue by nasht00** [kogosoftwarellc/open-api#350]
Can I specify a passport-js strategy as a securityHandler ?

So far it seems I need to wrap the `passport.authenticate` call and check for every kind of event it might throw as me.

Is there a way to treat the security handle as just a regular middleware so that express will know how to handle it out of the box?

**Comment by nasht00** [comment]
wrong issue

**Comment by jsdevel** [comment]
> Can I specify a passport-js strategy as a securityHandler ?

You can do whatever you want in the securityHandlers.  Please read the docs and examine the tests for [openapi-security-handler](https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-security-handler).

> Is there a way to treat the security handle as just a regular middleware so that express will know how to handle it out of the box?

You're free to use `app.use()` before you `.initialize`

**Comment by baophamtd** [comment]
Hi @jsdevel @NathanHazout sorry to bring this up, but I'm having issues trying to integrate with `passport`. It looks like I'm wiring it up incorrectly. Attached are my `app.js` and `{provider}.js` which is the path param that handles the authentication. The `GET` call is fired but it would not redirect to Facebook login but rather hanging. Would you mind to shed some light here?
`app.js`:
```
import express from 'express';
import { initialize } from 'express-openapi';
import swaggerUi from 'swagger-ui-express';
import path from 'path';
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';
import cors from 'cors';
import bodyParser from 'body-parser';
import passport from 'passport';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const app = express();
app.use(cors());
app.use(bodyParser.json());

initialize({
  app,
  apiDoc: fs.readFileSync(path.resolve(__dirname, './api/api-doc.yml'), 'utf8'),
  paths: path.resolve(__dirname, './api/v1/routes'),
  routesGlob: '**/*.{cjs,js}',
  routesIndexFileRegExp: /(?:index)?\.cjs$/,
});

app.use(
  "/api-documentation",
  swaggerUi.serve,
  swaggerUi.setup(null, {
    swaggerOptions: {
      url: "http://localhost:3000/v1/api-docs",
    },
  })
);

app.listen(3000);
```

`{provider.js}`
```
const authService = require('../../services/authService');
const passport = require('passport');
const FacebookStrategy = require('passport-facebook').Strategy;

module.exports = {
    get: [
        function (req, res, next) {
            next()
        },
        get,
    ],
};


function get(req, res) {
    if(req.params.provider == 'facebook'){
        passport.use(new FacebookStrategy({
            clientID: "ID",
            clientSecret: "secret",
            callbackURL: "http://localhost:3000/auth/facebook/callback"
          },
            function (accessToken, refreshToken, profile, done) {
                return done(null, profile);
            }
          ));
        passport.authenticate('facebook');
    }
}
```
