### ISSUE TITLE
Warning log : Ignoring the 2nd definition

### ISSUE THREAD

**Issue by fpozzobon** [kogosoftwarellc/open-api#368]
Hi,

not sure if I am using the library correctly, we are trying to define the openApi using : 
- YAML file 
- Operations 

## Problem : 
we get the warning `express-openapi: /health.get has already been defined. Ignoring the 2nd definition...`

## Expected : 
no warning

## Setup : 
```javascript
return EOA.initialize({
      app,
      apiDoc: path.resolve(__dirname, 'openapi.yaml'),
      operations: {
        getHealth: (req, res) => {res.json({'result': 'ok'})}
      }
    });
```

openapi.yaml :
```
paths:
  /health:
    get:
      operationId: getHealth
      description: Health check
      responses:
        200:
          description: ''
```

## Question : 
Are we miss using the library ?

**Comment by jsdevel** [comment]
@sebasmagri can you help on this one?

**Comment by sebasmagri** [comment]
@jsdevel sure, I'm also getting those warnings... will fix those.

**Comment by jsdevel** [comment]
thanks @sebasmagri !

**Comment by Manny651** [comment]
I'm not sure if this should be considered as the same issue, but the same warning appears if we have an apiDoc with the same paths defined in args.paths.

**Comment by Gino** [comment]
I also have the same issue, any updates on this?

**Comment by sebasmagri** [comment]
@Manny651 you mean you have the same paths in the apiDoc with operations and in path directories?

I'm sorry this has taken so long, have been dealing with some other priorities on this end.

If anyone want to complete testing the PR linked above please feel free.

**Comment by Manny651** [comment]
@sebasmagri yes, if we initialize with a complete apiDoc and use the "paths" options (not operations) to define the paths to the implementation, we get the same warning.

**Comment by leedm777** [comment]
You can also see these warnings during the `basic-usage-with-central-apiDoc` test.

```
$ npx mocha packages/express-openapi/test/sample-projects/basic-usage-with-central-apiDoc/spec.js 
<snip/>
express-openapi: /users.delete has already been defined. Ignoring the 2nd definition...
express-openapi: /users.post has already been defined. Ignoring the 2nd definition...
express-openapi: /apiDocs.get has already been defined. Ignoring the 2nd definition...
express-openapi: /users/{id}.get has already been defined. Ignoring the 2nd definition...
express-openapi: /users/{id}.post has already been defined. Ignoring the 2nd definition...
<snip/>
```

**Comment by jsdevel** [comment]
hoping to close this soon.  need to fix code coverage, then looking to publish

**Comment by jsdevel** [comment]
@sebasmagri 's fix in #370 actually broke express-openapi.  had to revert.  if anyone in the community can fix this issue it would be much appreciated.

**Comment by intelliot** [comment]
It seems like ignoring this warning has no ill effects on the server. Perhaps we can just remove the warning?

**Comment by jsdevel** [comment]
PRs are welcome

**Comment by seb-pereira** [comment]
Just pushed a PR: https://github.com/kogosoftwarellc/open-api/pull/479

**Comment by petriaarnio** [comment]
I'm still seeing this warning for `delete` path, because cannot define operation with the name `delete` in strict mode.
