### ISSUE TITLE
Invalid number parameters pass validation

### ISSUE THREAD

**Issue by Manny651** [kogosoftwarellc/open-api#371]
When a query or path parameter is defined as a number but the actual value cannot be converted (e.g. 'abc'), the parameter is converted to NaN and passes the request validator. NaN shouldn't be a valid value for a number (or integer) type.

**Comment by jsdevel** [comment]
indeed!  please submit a PR to fix this issue.

**Comment by Manny651** [comment]
I'm not sure how this case should be handled: should the request coercer convert the invalid value to null, or throw an error, or is it a request validator issue?

**Comment by jsdevel** [comment]
that's a great question.  i think i lean towards coercer.  how about you @Manny651 ?

**Comment by jsdevel** [comment]
i wonder though, would there be cases where you'd want to respond with a validation error?

**Comment by jsdevel** [comment]
perhaps the coercer shouldn't override the value if it can't be coerced into it's intended type?

**Comment by Manny651** [comment]
I think the best solution would be to prevent the coercer from overriding values that cannot be converted. That way, the request validator would respond with the appropriate error message for that case.

**Comment by jsdevel** [comment]
> I think the best solution would be to prevent the coercer from overriding values that cannot be converted.

i think i agree with that.  otherwise, the validator might be making assumptions and wouldn't have all the info to respond with an informative error.

please go ahead and update the coercer then.

**Comment by jsdevel** [comment]
published
