### ISSUE TITLE
Generated API doc fails Swagger validation when basePath is not set

### ISSUE THREAD

**Issue by Manny651** [kogosoftwarellc/open-api#376]
When configuring express-openapi, if the API's basePath option is not set, the generated API doc has the basePath property set to an empty string, which is invalid according to the swagger.io's online validator (the one used by default in Swagger UI).

According to the spec https://swagger.io/docs/specification/2-0/api-host-and-base-path/ : 
> [basePath] must start with a leading slash /. If basePath is not specified, it defaults to /

**Comment by jsdevel** [comment]
please submit a pr
