### ISSUE TITLE
initialize `paths` fails to resolve after webpack bundling

### ISSUE THREAD

**Issue by markserrano915** [kogosoftwarellc/open-api#378]
I have the following simplified initialize declaration:

```
const init = (app) => {
  initialize({
    app,
    apiDoc: v1ApiDoc,
    dependencies: {
      inventoryService: v1IventoryService
    },
    paths: './src/rest-api/api-v1/paths'
  });
};
```

When webpack bundles my project as one JS file, the bundled source gives me this:

```
...inventoryService:s.a},paths:"./src/rest-api/api-v1/paths"})}},
```
When I run my app, it breaks because it complains that it's unable to load the path because the original directory structure no longer exist. Everything is just one JS file. 

What's the best way resolve this problem? `paths` seems to accept only strings that are evaluated during runtime which works if the project is not bundled.

**Comment by markserrano915** [comment]
Nevermind. I think I found how:

```
import inventory from './api-v1/paths/inventory';
...
...

const init = (app) => {
  initialize({
    app,
    apiDoc: v1ApiDoc,
    dependencies: {
      inventoryService: v1IventoryService
    },
    paths: [
      { path: '/inventory', module: inventory }
    ]
  });
};
```

I compared the before and after and tested both setups, and I got the same expected result. On top of that webpack is happy.

**Comment by markserrano915** [comment]
I found another issue that's related to `webpack` and `difunc`. This time it's about the dependency injection.

The error is:
```
Error: e was not defined in dependencies
    at difunc (/node_modules/difunc/index.js:31:15)
    at Object.injectDependencies (/node_modules/openapi-framework/dist/src/util.js:217:12)
    at /node_modules/openapi-framework/dist/index.js:198:37
```

I have this `initialize` declaration for which has this `dependencies` property (which will be referenced by difunc):
```
const init = (app) => {
  initialize({
    app,
    apiDoc: v1ApiDoc,
    dependencies: {
      inventoryService: v1IventoryService
    },
    paths: ...
  });
};
```

Under the paths directory, I have the following file (as suggested in the docs):

inventory.js
```
export default function(inventoryService) {
    let operations = {
      GET
    };
...
```

When webpack bundler runs, the argument in the function is converted to the letter 'e'; however `difunc` is looking for 'inventoryService' instead and hence the error.

The solution I did was to take out the `dependencies` declaration from the `initiliaze` method and take out the service parameter from the paths directory. I then imported directly the `inventoryService`

```
import inventoryService from './foo/inventoryService';

export default function() {
    let operations = {
      GET
    };
```

**Comment by jsdevel** [comment]
the dependency injection is dependent on parameter names not getting mangled.

you probably need to define an absolute path to your paths directory.  it's relative to cwd but webpack is likely changing that.

not sure if there's much to do here, with the exception of the mangling issue.  that could be a feature request.
