### ISSUE TITLE
What about refactoring? ^_^

### ISSUE THREAD

**Issue by Santinell** [kogosoftwarellc/open-api#38]
To be honest I don't like the way which you choose for routing.
What about to make your router optional?
How can it be? For example:

```
openapi.initialize({
  apiDoc: require('./api-doc.js'),
  app: app,
  router: myRouter // if not set, by default it can be 'fs-routes'
});
```

If you don't mind, I can try to make PR

**Comment by jsdevel** [comment]
We have one issue where we'd like to allow operationHandlers instead of routesDir.  Would that suffice?

**Comment by Santinell** [comment]
If I could handle methods by operationId - yes.
Can I help with it?

**Comment by jsdevel** [comment]
> Can I help with it?

Of course!  Ideally I think we'd have a new initialization arg `operationHandlers`.  `operationHandlers` would be an object who's keys map to `operationId`s.

**Comment by Santinell** [comment]
How about a little change logic of using fsRoutes ?
Instead of read method by method and in same loop add midlewares, I propose to split it.
In first loop we union all apiDoc and generate array of objects like
for example: {method: "GET", path: "/host/status", handler: function(){ return true; }}

So after that we have same logic for operationHandlers - we no need to union, because we have full apiDoc file, and we just need to generate array with the same stucture.

**Comment by jsdevel** [comment]
@Santinell I like where you're going with this.

Here's my take on what's currently happening:
* We're building out the apiDoc
* We're adding middleware/routes to an express app

The problem as you've mentioned is that we're doing both of these things in the same loop.

In order to support a second strategy (args.operations) we need to:
1. Build the apiDoc using args.routes and/or args.operations.
2. Iterate over the apiDoc and generate middleware.
3. Use a handler from either `args.routes` _or_ `args.operations`.

For the third step, I feel `args.operations` should take precedence over `args.routes`.  So if `operationId` in an operations doc is a key to a handler in `args.operations`, we use that regardless of whether or not a handler was defined in the `args.routes` structure.

What do you think of this?  Am I summarizing what you said, but in a different way?

/me super excited to have you taking this on :smile:

**Comment by Santinell** [comment]
1) If args.operations contain only handlers like:
```
{
  "host.getByIP": function(ip){...},
  ...
}
```
then what should we add to apiDoc? handlers?

2) I think it would be better if args.routes and args.operations will work separately.
It's more clear and hard to imagine situation when you need both of them.

So I propose to do something like this:
```
if (args.routes) {
 //  Build the apiDoc (add docs and handlers)
} else if (args.operations) {
 //  Build the apiDoc (add handlers)
} else {
  throw new Error("Poof!");
}

// iterate over the apiDoc and add it to app as middleware

```

**Comment by jsdevel** [comment]
Yea, working separately should be fine.  We can at least start with that and handle them working in tandem later if requested.

**Comment by Santinell** [comment]
And what do you think about wild-card handler?
It would be nice if I could do for example:
```
{
  "*": function generalHandler(operationId, args) {}
}
```
For all paths will be the same handler which will dynamically call that required

**Comment by jsdevel** [comment]
I kind of feel it's better to be explicit.  Form a consumer perspective, I'd like to know what operation is getting called.  With a wildcard that we apply, I don't feel that's known.

so if you want to have the same handler used for multiple operations, then I feel each operation should have the same operationId.

**Comment by Santinell** [comment]
I want to have just one handler for all operations, because my methods inside classes, not in array.
For example: operationId = 'host.getByIP', this means that class Host has method getByIP.

```
function generalHandler(operationId, args) {
  return  function(req, res, next) {
    const [className, methodName] = operationId.split('.');
    const obj = new classes[className](req.user);
    obj[methodName].apply(obj, args).then(result => {
      res.send(result);
    }).catch(next);
  };
}
```

**Comment by jsdevel** [comment]
So in your apiDoc, you'll reference it with `operationId: 'generalHandler'`.  Then when you initialize, just pass `{operations: {generalHandler: function(req, res, next) {}}}`

**Comment by Santinell** [comment]
But I use operationId to define class and method, which I need to use...
I can't do that.

**Comment by Santinell** [comment]
Besides operationId must be unique - is a requirement of the standard

**Comment by jsdevel** [comment]
well, there'd really be nothing stopping you from just re-using the same handler, but I don't feel a wildcard would be good.

**Comment by Santinell** [comment]
Maybe another argument? 
args.defaultHandler - if no handlers from routes or operations we use it

**Comment by Santinell** [comment]
if save operationId in req, then we can use handler without wrapper
```javascript

const defaultHandler = function (req, res, next) { 
  next(new Error(`Method for operation ${req.method} ${req.url} not found. 
operationId = ${req.operationId}`));
}

if (args.defaultHandler && typeof args.defaultHandler === "function") {
  defaultHandler = args.defaultHandler;
}
```

**Comment by jsdevel** [comment]
args.defaultHandler would work.

**Comment by jsdevel** [comment]
I'm not sure what you mean by wrapper.  Exposing arrays is optional.  It's just a way to precede your handler with business specific middle ware.  Array or function should be accepted.

**Comment by jsdevel** [comment]
Also, keep in mind that we're _not_ going to be using es6 syntax features until v0.10 and v0.12 have been deprecated.

**Comment by marcofranssen** [comment]
Why no es6 if there is also babeljs to tranpile back to es5?

**Comment by jsdevel** [comment]
> Why no es6 if there is also babeljs to transpile back to es5?

There certainly can be.  It's mainly just more setup to add babel, but things that can natively be supported would probably be quick wins.

**Comment by jsdevel** [comment]
closing this for the following reasons:

* Typescript is now extensively used herein (#174)
* Changes to the wiring up of paths and operations can go in https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-framework.  PRs are welcomed :smile:
