### ISSUE TITLE
Why request validation can't be done without parameters

### ISSUE THREAD

**Issue by javierblancosp** [kogosoftwarellc/open-api#381]
### Problem

I have endpoints with only the requestBody, no parameters. Why i'm forced to define a parameters list to use request validator?

https://github.com/kogosoftwarellc/open-api/blob/275997662d9382492f6e7658fb7a3c1776eb4892/packages/openapi-request-validator/index.ts#L56

**Comment by jsdevel** [comment]
I'd say this is a defect for OpenAPI V3 documents.  Can you open a PR?

**Comment by javierblancosp** [comment]
Sure
