### ISSUE TITLE
request validator: readonly & required properties throwing validation error in request body

### ISSUE THREAD

**Issue by BrandonFitzgibbon** [kogosoftwarellc/open-api#389]
For OpenAPI 3, when defining a schema in the component section with a property that is both readonly and required, the request validator will return a bad request when that property is missing from the request body.

I'm currently handling this by removing all readonly property keys from the required array of the schema before passing it to ajv.compile as the body schema, but it's not very elegant, fragile and untested.

example schema stub for failing validation:

```
    requestBody:
        required: true
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/Thing'

    schemas:
        Thing:
            required:
                - id
                - name
             properties:
                 id:
                     type: number
                     readonly: true
                 name:
                     type: string
```

The OpenAPI 3 spec allows for this sort of behavior, so I'm unsure whether this is intended or not.

**Comment by jsdevel** [comment]
@BrandonFitzgibbon v3 the community is still working out the v3 kinks, and this sounds like one of them.  if you have the time, we'd greatly appreciate a pr to fix this.
