### ISSUE TITLE
[openapi-default-setter] Populate defaults in request body

### ISSUE THREAD

**Issue by TuckerWhitehouse** [kogosoftwarellc/open-api#404]
Breaking out into a separate issue from https://github.com/kogosoftwarellc/open-api/pull/398#issuecomment-478292795

The openapi-default-setter package does not support setting defaults in the request body. Ajv (which is used by openapi-request-validator) has a `useDefaults` option, but it sounds like adding support for setting body defaults in the openapi-default-setter package is preferred.

Thoughts on where to begin or prior art to take inspiration from?

**Comment by jsdevel** [comment]
i'd say just hardcode the passing of useDefaults to AJV for now.

**Comment by TuckerWhitehouse** [comment]
So I couldn't find a way to pass options to ajv (or pass in a custom instance), which lead me to patching all of the methods on the prototype to add `useDefaults` -- if you can recommend an alternative approach I'm all ears :)

```js
for (const method in Ajv.prototype) {
  const _method = Ajv.prototype[method]
  Ajv.prototype[method] = function() {
    if (!('useDefaults' in this._opts)) this._opts.useDefaults = true
    return _method.apply(this, arguments)
  }
}
```

**Comment by jsdevel** [comment]
can we just pass that in everywhere that we call an ajv method?

**Comment by TuckerWhitehouse** [comment]
Oh I think I misunderstood - were you saying do a PR in this project to set `useDefaults` on the Ajv constructor? I'm not sure if there are any side-effects to that - I was thinking maybe it would be possible to set that value based on the presence of the `openapi-default-setter` middleware, and as long as that hadn't been disabled apply `useDefaults` to Ajv - thoughts?

**Comment by jsdevel** [comment]
> were you saying do a PR in this project to set useDefaults on the Ajv constructor?

yes

**Comment by jsdevel** [comment]
i'm OK changing the options we pass to the contructor/methods, i'm just not ok coupling the interfaces herein with ajv directly wherever possible
