### ISSUE TITLE
Access to req.operationDoc in securityHandler

### ISSUE THREAD

**Issue by ashtarcommunications** [kogosoftwarellc/open-api#429]
I'd like to be able to access req.operationDoc in a securityHandler. I don't need any body parsing or parameter validation at that point, but it would be great to access the operation definition when figuring permissions.

Basically, I want to define a vendor-prefixed schema extension for operation-level permissions, and then access that definition in the central security handler and be able to send a 401 before actually getting to the operation handler.

It looks to me like the result of #286 is that the security middleware is now run before any API doc validation at all, which would make this impossible?

**Comment by jsdevel** [comment]
well, if any part of the api doc is invalid, the application won't start up.  i'm thinking we could just change the ordering to make it available in the request.  feel free to open a pr for that.

**Comment by ashtarcommunications** [comment]
Makes sense. PR #430 should do it, but if I'm missing something important about the exact middleware ordering, let me know.

**Comment by ashtarcommunications** [comment]
Realized I didn't include a version bump in the package.json, but I reread the contribution guidelines and it looks like something that's handled on the maintainer side?

**Comment by jsdevel** [comment]
yea, i'll handle the bump when i publish.  probably tonight
