### ISSUE TITLE
errorMiddleware is only registered when exposeApiDocs is truthy

### ISSUE THREAD

**Issue by vollmant** [kogosoftwarellc/open-api#435]
Currently the `errorMiddleware` function is registered only if `exposeApiDocs` is truthy. Shouldn't `errorMiddleware` be called regardless of the value set for `exposeApiDocs`?

https://github.com/kogosoftwarellc/open-api/blob/da7a83f6d3690dc4e82cc45bc51c25c7ff895a42/packages/express-openapi/index.ts#L106

**Comment by jsdevel** [comment]
yes.  please open a PR @vollmant

**Comment by seb-pereira** [comment]
Hi,
I needs `errorMiddleware` to get registered when `exposeApiDocs` is disabled, so I pushed a PR.

**Comment by jsdevel** [comment]
i'll publish soon
