### ISSUE TITLE
Bad error message if operationId is not specified

### ISSUE THREAD

**Issue by michaellperry** [kogosoftwarellc/open-api#465]
When calling `initialize` with an `apiDoc` that has an operation that is missing an `operationId`, express-openapi emits a warning and then throws an exception. The warning is:

> Operation undefined not found in the operations parameter

The exception is:

> TypeError: Cannot read property 'undefined' of undefined

Neither is helpful in identifying the problem.

I have traced this issue into openapi-framework, so it is not specific to express-openapi.

**Comment by jsdevel** [comment]
@michaellperry please submit a PR with a more descriptive message.
