### ISSUE TITLE
v3: Consumes is not set correctly when operation refer to requestBody with a $ref

### ISSUE THREAD

**Issue by jgranstrom** [kogosoftwarellc/open-api#486]
When setting the `requestBody` of an operation with a $ref such as:
```
// Operation
{
  requestBody: { $ref: '#/components/requestBodies/SomeBody' }
}

// Doc
{
  requestBodies: {
    SomeBody: {
       content: {
         'application/json': { schema: { type: 'object' }}
       }
    }
  }
}
```

The `consumes` property for the operation context fails to include the media type, making any `consumesMiddleware` for the media type silently not run for the operation.

This code seems to not resolve $refs if any before determining the consumed media types for operations.
https://github.com/kogosoftwarellc/open-api/blob/b01f1a637b2c621221a8b269f6047cd378b7c384/packages/openapi-framework/index.ts#L379-L388

**Comment by jsdevel** [comment]
please submit a PR @jgranstrom

**Comment by jgranstrom** [comment]
@jsdevel sure thing, #488 adds support for this case.
