### ISSUE TITLE
Nullable properties in Swagger 2.0

### ISSUE THREAD

**Issue by adrianplavka** [kogosoftwarellc/open-api#493]
Hello,

I have an issue regarding `openapi-request-validator`.

Since `nullable` fields are not supported in Swagger 2.0, is there any way we could supply some sort of vendor extension (like `x-nullable`) into a schema? The validator would read the custom extension and therefore allow `null` values.

Use case - suppose we have a schema defined like this:
```json
"UserDomainView": {
    "properties": {
        "name": {
            "type": "string"
        },
        "key": {
            "type": "string"
        },
        "id": {
            "type": "number",
            "format": "double"
        },
        "description": {
            "type": "string",
            "x-nullable": true
        }
    },
    "required": [
        "name",
        "key",
        "id"
    ],
    "type": "object"
}
```

Suppose, we sent a request body, like:
```json
{
    "name": "Some name",
    "key": "1",
    "id": 2898,
    "description": null
}
```

The validator will yield an error, stating that the `description` property has to be a string.

**Comment by jsdevel** [comment]
please open a PR

**Comment by adrianplavka** [comment]
I certainly can. 

What kind of API do you think would be the best? I was thinking about creating another property in `args`, called, let's say, `vendorExtensions`. For now, the only property would be `nullable`, which would require a string key for where to look for a vendor-supplied nullable property.

When iterating over properties of a schema, we would look for these vendor extensions & apply specific actions. In our case, it would mark the property as nullable.

I can't think of any other vendor extension case, but this could be handy for other future cases.

**Comment by jsdevel** [comment]
wait, i'm sorry, there's actually a way to handle this right now

**Comment by jsdevel** [comment]
you can use oneOf: https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi#extending-openapi-schema

**Comment by jsdevel** [comment]
checkout this sample project: https://github.com/kogosoftwarellc/open-api/blob/master/packages/express-openapi/test/sample-projects/with-schema-extension/api-doc.js

**Comment by adrianplavka** [comment]
The usage looks really weird. 

OpenAPI specifies a set of allowed types and "null" isn't one of them. How is that a valid OpenAPI document?

Nonetheless, the example you posted tries to solve the same issue, but, in my opinion, in a much verbose way. I think a much better solution would be to support `x-nullable` out of the box (some vendor tools already support it) or provide users to override this default vendor extension.

**Comment by jsdevel** [comment]
@adrianplavka so the underlying validator framework is jsonschema.  OpenAPI v2 didn't allow oneOf, even though it's all based on jsonschema and oneOf is perfectly fine in jsonschema.  At this point with OpenAPI v3 supporting nullable, adding x-nullable to v2 may just add more confusion to the code base, but if you'd like to do that feel free to open a PR.

**Comment by akinnee** [comment]
In case anyone still needs this, I wrote this little function to modify the swagger doc to use oneOf:
```
const convertXNullableToOneOf = (swaggerDoc: OpenAPIV2.Document) => {
  if (swaggerDoc.definitions) {
    Object.values(swaggerDoc.definitions).forEach((modelDef) => {
      if (!modelDef.properties) return;
      Object.entries(modelDef.properties).forEach(([propName, propDef]) => {
        if (!modelDef.properties) return;
        if (propDef['x-nullable']) {
          modelDef.properties[propName] = {
            oneOf: [propDef, { type: 'null' }],
          };
        }
      });
    });
  }
};
```
