### ISSUE TITLE
args.paths breaks when using Typescript

### ISSUE THREAD

**Issue by pontusr** [kogosoftwarellc/open-api#494]
Paths supplied to args.paths are supposed to be relative to the "project root". In our environments this means `args.paths: './src/handlers'` works during development (towards our *.ts handlers) and `args.paths: './dist/handlers'` during runtime (towards our *.js) files.

We prefer using ts-node during development to avoid having to build the js files and serve them on each change.

Any suggestion for a setup that offers a good workflow?

```typescript
import * as express from "express";
import * as bodyParser from "body-parser";
import { initialize } from "express-openapi";

ionst app = express()
app.use(bodyParser.json())

initialize({
  apiDoc: require('./api-docs/api-doc.json'),
  app,
  paths: './src/handlers'
});

app.listen(3000, () => {
  console.log('server started on port 3000')
})
```

It seems args.apiDoc works thanks to require being able to find a file/module - not sure this is the intended way here.

**Comment by jsdevel** [comment]
> Any suggestion for a setup that offers a good workflow?

hmm, no, but if anyone else does or if you find a good solution please submit a PR to update the README with an example.

**Comment by Nox-404** [comment]
@pontusr We added `TS_NODE=true` before each run command in development (`dev, test, coverage`) and we have this for the initialize:
```

const pathOptions = process.env.TS_NODE === 'true' ? {
  paths: 'src/handlers',
  routesGlob: '**/*.ts',
  routesIndexFileRegExp: /(?:index)?\.ts$/,
} : { paths: 'dist/handlers' };

initialize({
  /* other settings */
  ...pathOptions,
});

```

**Comment by pontusr** [comment]
Thank you @Nox-404, I will try that!

@jsdevel Since this can be solved with other tooling I don't think this is really an issue with this library at all. I'm happy to create a PR adding some guidance but I don't see the right spot for that, any suggestions?

**Comment by jsdevel** [comment]
@pontusr anything you can add to the READMEs would be super helpful and welcomed!  Use your best judgement!
