### ISSUE TITLE
Wrong type definition for OperationHandlerArray

### ISSUE THREAD

**Issue by Nox-404** [kogosoftwarellc/open-api#496]
Hello,
When defining operations in *typescript* we can use the type `Operation` which is either `OperationFunction | OperationHandlerArray`.

The problem is that `OperationHandlerArray` is an `OperationFunction[]`. The apiDoc property becomes a property of every elements of the array instead of the whole array.

Here is the project `@types/express-openapi` with the correct typing : https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-openapi/index.d.ts#L266

Is it possible to fix that typing issue ?
It prevents the use of `apiDoc` on endpoints with middlewares.

Thanks

**Comment by jsdevel** [comment]
@Nox-404 please submit a PR

**Comment by Nox-404** [comment]
@jsdevel Got it

**Comment by miklosaubert** [comment]
@jsdevel Will this fix be released soon? I ran into this issue with the latest version of express-openapi (4.6.5).

**Comment by jsdevel** [comment]
@miklosaubert hoping to get to this in the next couple of days.  please continue to pester me.

**Comment by miklosaubert** [comment]
> @miklosaubert hoping to get to this in the next couple of days. please continue to bump this if i don't get back to you within that timeframe.

Well here's a bump then :)

**Comment by jsdevel** [comment]
thanks @miklosaubert !  i'll likely publish today

**Comment by miklosaubert** [comment]
thanks @jsdevel ! Just noticed the new version :)

**Comment by jsdevel** [comment]
thanks for the bump!
