### ISSUE TITLE
UnhandledPromiseRejectionWarning when async route handler gets rejected

### ISSUE THREAD

**Issue by pjpsoares** [kogosoftwarellc/open-api#510]
Imagine you have a rejected promise as a result of processing the request, you get an UnhandledPromiseRejectionWarning. Wouldn't it be ideal to catch that and send as a normal error, so that the error middleware can take care of that?
With some code, imagine you have a get function like 
```
async function get(req, res, next) {
  throw new Error('some error');
}
```
if I set this to handle my request it will throw an UnhandledPromiseRejectionWarning, but I believe in a perfect world this should be wrapped in something like 
```
  try {
   await get(...);
  } catch (error) {
    next(error);
  }
```
That way I wouldn't have to do this for every route I have. Is there any downside to it? Would you guys accept a PR for this?

**Comment by jsdevel** [comment]
no.  express has error handling middleware built in to do this.

**Comment by jsdevel** [comment]
https://expressjs.com/en/4x/api.html#router.use  look for `Error-handling middleware`

**Comment by pjpsoares** [comment]
I know the middleware, I have the middleware, but it does nothing as the function returns a promise (rejected) and not an exception.
The express-openapi actually calls the route handler function, so it's the only place you could handle it gracefully, by catching the rejected promise and send it as a normal error, if not you force all functions to actually try catch the code and do that.

**Comment by jsdevel** [comment]
@pjpsoares have you tried enabling promise mode in the options?

**Comment by jsdevel** [comment]
https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi#argspromisemode
