### ISSUE TITLE
Same API for openapi-response-validator and openapi-request-validator 'validate'

### ISSUE THREAD

**Issue by AlexHolly** [kogosoftwarellc/open-api#512]
I noticed a few differences, is it possible to make them more similar?

- Name both `validate` or `validateRequest / validateResponse`

  - **openapi-request-validator:**

    `validator.validate`

  - **openapi-response-validator:**

    `instance.validateResponse`

- The return type for `validate`:
   
  - in `request-validator` can be an Array or Object.

       https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-request-validator/index.ts#L314

  - in `response-validator` is always an Object but sometimes the `errors` key is missing.
       https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-response-validator/index.ts#L124
      https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-response-validator/index.ts#L132

   It would be nice to always get an Array.

**Comment by jsdevel** [comment]
submit a PR!
