### ISSUE TITLE
[openapi-types] Paths entry in OpenAPIV2 can be any type

### ISSUE THREAD

**Issue by SkaceKamen** [kogosoftwarellc/open-api#552]
I'm referencing this:
https://github.com/kogosoftwarellc/open-api/blob/59ed9d734487f873bed6f865571506958991dd51/packages/openapi-types/index.ts#L503
paths entry in OpenAPIV2 has following type:
```typescript
PathItemObject | any
```
This breaks the typing in strict mode, since the entry will be just considered as `any`.

Is the `| any` intentional?

**Comment by jsdevel** [comment]
not sure.  feel free to open a PR
