### ISSUE TITLE
Request and Response Errors message

### ISSUE THREAD

**Issue by AlexHolly** [kogosoftwarellc/open-api#554]
- The `message` is different

Request:
```
- path: 'numbers[0]'
      errorCode: multipleOf.openapi.validation
      message: should be multiple of 2
      location: body
```

Response:
```
- path: 'numbers[0]'
      errorCode: multipleOf.openapi.responseValidation
      message: 'numbers[0] should be multiple of 2'
```
I suggest removing this part `validationError.path + ' '`
https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-response-validator/index.ts#L210

- Also the errorCode should look the same `validation `to `requestValidation`

`errorCode: multipleOf.openapi.validation`
https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-request-validator/index.ts#L435

errorCode: `multipleOf.openapi.responseValidation`,
https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-response-validator/index.ts#L200

**Comment by jsdevel** [comment]
feel free to open a pr
