### ISSUE TITLE
[openapi-request-coercer] maybe strict-er coercion rules?

### ISSUE THREAD

**Issue by nulltoken** [kogosoftwarellc/open-api#567]
Currently some strict coercion rules might even be enforced:

**boolean:** `"trUE"` would be considered valid and coerce to `true`
**integer:** no strict version exists and the current one would consider `"17.02"` as a valid entry and coerce to `17`

Proposal would be to 
- Either
  - make the strict boolean rule.. well.. strict :wink:
  - introduce a strict integer rule
- Or
  - allow the caller to inject a coercion strategy object (that would only expose simple primitive types (ie. `boolean`, `number` and `integer`)) that would override the built-in ones.

FWIW, I'd be more in favor of the second option (which would not introduce any breaking change while putting the caller in complete control). Thoughts?

Would you be open to this change, I'd gladly craft a PR to make that happen.

**Comment by jsdevel** [comment]
i'd be in favor of the latter as well

**Comment by nulltoken** [comment]
> i'd be in favor of the latter as well

Thanks for the feedback. I'll work on a PR along those lines.
