### ISSUE TITLE
Load OpenAPI 2.0 Schema into OpenAPIResponseValidator

### ISSUE THREAD

**Issue by evan111** [kogosoftwarellc/open-api#578]
Hi,

Maybe a dumb question, how do you load an OpenAPI 2.0 schema into the openapi-response-validator:
i.e.
```
const swaggerSpec = require('./spec.json')
var responseValidator = new OpenAPIResponseValidator(swaggerSpec);
```
It's clear this does not work, is there a parser that can transform an OpenAPI spec into the required constructor argument?

Thanks,

Evan

**Comment by jsdevel** [comment]
look at the source.
