### ISSUE TITLE
OpenAPIV2.SecuritySchemeOauth2Base is missing type specification

### ISSUE THREAD

**Issue by karlvr** [kogosoftwarellc/open-api#623]
Could you please add `type: 'oauth2'` to `OpenAPIV2.SecuritySchemeOauth2Base`?

That way TypeScript would correctly narrow the type of `OpenAPIV2.SecuritySchemeObject` down to `OpenAPIV2.SecuritySchemaApiKey` when you check `if (schema.type === 'apiKey')`.

**Comment by jsdevel** [comment]
i can't but you can!  feel free to submit a pr @karlvr !
