### ISSUE TITLE
Is there a release timeframe?

### ISSUE THREAD

**Issue by littldr** [kogosoftwarellc/open-api#652]
Hi,

first thanks for the package! It really makes working with OpenAPI and Express an ease!

But I stumbled over some bugs and while investigating the cause, I found that they are already fixed and merged in this repo, but not released yet.

Is there a plan to release the latest changes soon?
Or do you need help with it? If yes, tell me what's missing and I will try to invest some time. :)

**Comment by jsdevel** [comment]
i tend to batch releases, as this repo gets a number of PRs frequently.  i have been meaning to switch to learna though to make the release process faster.  any suggestions you have on managing the monorepo to make the release process easier are welcomed.

**Comment by littldr** [comment]
Thanks for your answer!
I do not have any relevant experience with managing a monorepo, so I cannot recommend any tools or best practices. 

But [lerna](https://github.com/lerna/lerna) looks very promising. Have you already started digging into this topic or may should I give it a try?

**Comment by jsdevel** [comment]
lerna is in.  just published 7.0.0.  publishes should happen _much_ faster now.
