### ISSUE TITLE
Latest published openapi-jsonschema-parameters package (1.2.0) isn't the same as 1.2.0 in this repository?

### ISSUE THREAD

**Issue by kwakwaversal** [kogosoftwarellc/open-api#662]
I could be missing something, but the `openapi-jsonschema-parameters` in `master` is version [1.2.0](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-jsonschema-parameters/package.json#L3). The dependency used by `openapi-request-validator` is [1.2.0](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-request-validator/package.json#L32).

But the published version is at odds with what is in master for `1.2.0` on a content delivery network e.g.,
https://cdn.jsdelivr.net/npm/openapi-jsonschema-parameters@1.2.0/dist/index.js. Specifically the [SUBSCHEMA_KEYWORDS](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-jsonschema-parameters/index.ts#L87) identifer is nonexistent in the published version of `openapi-jsonschema-parameters`?

An I missing something obvious or has it been pushed under the wrong version?

I've spent more time than I care to admit trying to get OpenAPI v3 parameter `deepObject` to work, and I was "fixing"/debugging the wrong file in my `node_modules`. Would be great to know either way if this is an issue as I would like to take advantage of `properties` and `additionalProperties` in sub schemas.

Cheers.

**Comment by iggh** [comment]
So after further digging, it looks like the work I need was done in Feb in the MR https://github.com/kogosoftwarellc/open-api/pull/621

[openapi-jsonschema-parameters](https://www.npmjs.com/package/openapi-jsonschema-parameters) was last published 7 months ago so I would assume that just means that the changes haven't been published yet.

@jsdevel is there a release cycle to get the latest version of `openapi-jsonschema-parameters` out?

**Comment by kwakwaversal** [comment]
After some digging, it looks like the work I need was done in Feb in the MR https://github.com/kogosoftwarellc/open-api/pull/621

[openapi-jsonschema-parameters](https://www.npmjs.com/package/openapi-jsonschema-parameters) was last published 7 months ago so I would assume that just means that the changes haven't been published yet.

@jsdevel is there a release cycle to get the latest version of `openapi-jsonschema-parameters` out?

**Comment by morriskimani** [comment]
I have the exact same issue @kwakwaversal. Were you able to make any progress regarding this?

**Comment by jsdevel** [comment]
7.0.0 is out.  first release/publish using lerna!  please lmk if it's all working correctly.  now that we have lerna setup, publishes should happen a lot faster.  the old process was too tedious for me.  now it's joyful :joy:
