### ISSUE TITLE
Released: JSON Schema for the OpenAPI 3.0 Specification

### ISSUE THREAD

**Issue by mahnunchik** [kogosoftwarellc/open-api#676]
JSON Schema for the OpenAPI 3.0 Specification have beed released https://github.com/OAI/OpenAPI-Specification/issues/1032

Readme may be changed https://github.com/kogosoftwarellc/open-api/tree/master/packages/express-openapi

**Comment by jsdevel** [comment]
@mahnunchik can you open a PR to change it please?
