### ISSUE TITLE
Request coercer is unable to handle OpenAPI V3 object serializations

### ISSUE THREAD

**Issue by foxfriends** [kogosoftwarellc/open-api#686]
Currently, when used through `express-openapi` or `openapi-framework`, it appears object coercion must be enabled via a flag, and this enables only the "default" `JSON.parse` object coercion.

OpenAPI V3 specifies [parameter serializations](https://swagger.io/docs/specification/serialization/#query) for objects in the query parameters, which could intuitively be enabled by default, rather than only providing the `JSON.parse` method. This would make object coercion more in line with arrays (which are already supported).

In particular, when encoded using `deepObject` style, the object seems to already be deserialized into an object correctly, and so it should be fairly easy to coerce the properties recursively. Form-style objects (whether exploded or not) are not deserialized, but the OpenAPI documentation states that existing URI template libraries can be used to handle the serialization, so this may be an option there which could also be extended to cover array deserialization.

**Comment by jsdevel** [comment]
please submit a pr
