### ISSUE TITLE
Support for OpenAPI 3.0.0?

### ISSUE THREAD

**Issue by bkyarger** [kogosoftwarellc/open-api#72]
Any plans in the works to support 3.0.0?

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/README.md

Looks like it's expected to be released in July.

**Comment by jsdevel** [comment]
Been monitoring that.  Once the spec is finalized, I think we'll setup some milestones.

**Comment by jsdevel** [comment]
@MugeSo Looks like the [3.0.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) is finally here!

**Comment by jsdevel** [comment]
Looks like they haven't published an official jsonschema document yet (see https://github.com/OAI/OpenAPI-Specification/issues/1301).

**Comment by jeffswitzer** [comment]
+1 looking to set up a new openapi 3 express project

**Comment by sethwenzel** [comment]
Any word on this?  Sure would be handy to describe webhooks for subscriptions...

**Comment by jsdevel** [comment]
We're still waiting for a finalized version.  We _could_ base an implementation off of the beta schema they have in PR, but I'm somewhat reluctant to do that.  Let me know what you guys think.

**Comment by sethwenzel** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md
https://swagger.io/announcing-openapi-3-0/
-- isn't that released?

**Comment by jsdevel** [comment]
> -- isn't that released?
Do you have a stable jsonschema file?  See my [issue](https://github.com/OAI/OpenAPI-Specification/issues/1301)

**Comment by sethwenzel** [comment]
Ah well i'm with you then, they need to provide a schema if it's really released.

**Comment by h2non** [comment]
Any updates here? What's the approximated cost for upgrading the package?

**Comment by jsdevel** [comment]
I'm hoping the changes aren't too huge.  Haven't seen progress on the OAI ticket.

**Comment by vasergen** [comment]
Any updates here?

**Comment by jsdevel** [comment]
FYI, @blortfish has an initial PR ready for the validation https://github.com/kogosoftwarellc/openapi-schema-validation/pull/1

**Comment by jsdevel** [comment]
OpenAPI v3 is now supported.  Any issues relating to it should be reported in new issues.
