### ISSUE TITLE
Swagger UI route or additional work needed?

### ISSUE THREAD

**Issue by danactive** [kogosoftwarellc/open-api#724]
What is the URL path for Swagger UI? I integrated [basic sample](https://github.com/kogosoftwarellc/open-api/tree/2276673b41fee05217f4c885b18207122c858420/packages/koa-openapi/test/sample-projects/basic-usage) of koa-openapi into koa app server. In the express docs I see this reference
> Adds a route for Swagger UI (apiDoc.basePath + args.docsPath).

http://localhost:3000/v1/api-docs
- shows OpenAPI JSON spec with `World` definition and `users` path

http://localhost:3000/swagger
http://localhost:3000/swagger-ui
http://localhost:3000/v1/swagger
http://localhost:3000/v1/swagger-ui
- 404, I expect to see the Swagger UI similar to this screenshot but `users` not `pets`
![Sample Swagger UI](https://user-images.githubusercontent.com/1093286/113034166-a2ccc880-9146-11eb-9b68-984a894c0ebb.png)

**Comment by elliotdickison** [comment]
The route provided by `express-openapi` at `apiDoc.basePath + args.docsPath` serves data that Swagger UI can use to generate documentation, but Swagger UI is a completely separate project. To set up Swagger UI with Express and `express-openapi` try install the [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express) package and then follow the ["Load swagger from url"](https://www.npmjs.com/package/swagger-ui-express) instructions to load data from the `docsPath` endpoint provided by `express-openapi`.

**Comment by danactive** [comment]
The extra work needed was very minimal. Simply add `koa2-swagger-ui` for koa app servers
