### ISSUE TITLE
[express-openapi] text/plain content in requestBody gives an error

### ISSUE THREAD

**Issue by eyzi** [kogosoftwarellc/open-api#741]
Hey. I'm trying to send a plain text PATCH request but express-openapi gives me an error that the body "should be string". Is this a bug or am I doing something wrong?

Here's what I have in the YAML file, a sample request, and the response that I get back. For context, this API request (`PATCH /links/{id}`) is used to update the link `id` with the plain text parameter in the body.

api-doc.yml:
```yml
...
requestBody:
  description: Plain text parameter
  required: true
  content:
    text/plain:
      schema:
        type: string
...
```

sample request (sent via Postman):
```
curl --location --request PATCH 'https://api.example.com/links/google' \
--header 'Content-Type: text/plain' \
--data-raw 'https://google.com'
```

response:
```js
{
  status: 400,
  errors: [
    {
      errorCode: 'type.openapi.requestValidation',
      message: 'should be string',
      location: 'body'
    }
  ]
}
```

It works if I do it with `application/json` instead. Though, I'd like to get it working with `text/plain` if possible.

**Comment by Swizec** [comment]
For anyone else who finds this thread, I was missing `text/plain` support in my Express stack.

This fixed it:

```javascript
.use(BodyParser.text({ type: 'text/*' }))
```
