### ISSUE TITLE
Property 'default' of type 'Response | undefined' is not assignable to string index type 'Response'

### ISSUE THREAD

**Issue by mirceanis** [kogosoftwarellc/open-api#742]
using package `open-api` in a project with `"strict": true` in `tsconfig.json` causes the error:
```
Property 'default' of type 'Response | undefined' is not assignable to string index type 'Response'
```

It would seem that explicitly accepting `undefined` in `ResponsesObject` fixes it:
```typescript
  export interface ResponsesObject {
    [index: string]: Response | undefined;
    default?: Response;
  }
```

This happens since version 9.0.0

**Comment by dnalborczyk** [comment]
encountered the same issue.

the interface defines that all indexers have the same signature, with `default?` also returning `undefined`, it deviates from the indexer definition.

https://stackoverflow.com/questions/45258216/property-is-not-assignable-to-string-index-in-interface

**Comment by mirceanis** [comment]
I don't know about the intents here. I proposed this fix purely from a typescript strict compilation perspective.
I suppose it would also work if `default` is always expected:
```typescript
export interface ResponsesObject {
  [index: string]: Response;
  default: Response;
}
```

**Comment by Kosta-Github** [comment]
`default` is definitely optional, therefore `default?: Response` is required.

IMHO, `[index: string]: Response | undefined` is reasonably, since you will not get a `Response` object back for a random `string`, e.g., `resp['bla']` or `resp.hello` ... therefore, you should be "forced" to check for `undefined`...

**Comment by henhal** [comment]
Record types where the key is _all strings_ is bound to cause problems: `Record<string, X>` or `{[key: string]: X}` both mean that you may index the type with _any string_ and expect to get an `X` back.

So in this case, the type specifies that every value of type `ResponsesObject` has the properties `foo`, `bar` and `lolcat`, and all other infinite combinations of characters that form strings ...

For types where the key range is not a known union or similar, you'd better use `| undefined` on the values.
Also, if doing that, in this case, adding the `default` property at all is redundant.

This should do?

```
interface ResponsesObject {
  [index: string]: Response | undefined;
}
```

**Comment by mirceanis** [comment]
Please ignore my second "solution". It only satisfies the typescript compiler, but doesn't reflect reality in any way.

The actual solution I'm proposing is in the description of this issue and also in PR #743

Thank you for the `skipLibCheck` workaround, @henhal. I'll try that.

**Comment by henhal** [comment]
Thanks @mirceanis, I hadn't seen the PR. Great work.

**Comment by Morl99** [comment]
@jsdevel  I don't mean to be pushy, but if there is any chance that you could take a look at the linked PR, it would be really helpful. For the moment, we are blocked to update to 9.0.2 because of this.

Thank you for your hard work!
