### ISSUE TITLE
Changelogs outdated

### ISSUE THREAD

**Issue by deyhle** [kogosoftwarellc/open-api#777]
Apparently there are CHANGELOG.md files in each package folder, however they seem unmaintained.
For example express-openapi:
https://github.com/kogosoftwarellc/open-api/blob/master/packages/express-openapi/CHANGELOG.md
Current version is 9.3.1, changelog ends at 6.0.0.
Is it safe to update to 9.3.1? Were there breaking changes I need to address in code?

**Comment by jsdevel** [comment]
it's been pretty maintenance heavy to keep up to date with the changelogs.  generally, i only do major version updates when there are breaking changes i.e. the project follows semver.

**Comment by deyhle** [comment]
I see, so from 6 to 7 to 8 to 9 there where 3 major updates with breaking changes? Which changes were that?

**Comment by jsdevel** [comment]
This is an open source project that I donate my time to.  With everything going on in my life I don't have the time to keep the changelog up to date.  If you would like to figure out a solution for that I would be totally open to it.  My suggestion in the interim: 
 look at the commit history on the master branch.  It's pretty clean (I squash each commit in the PRs when merging them).
