### ISSUE TITLE
initialize() of express-openapi 12.0.0 always throws exception on Windows

### ISSUE THREAD

**Issue by renkei** [kogosoftwarellc/open-api#812]
After the update to express-openapi 12.0.0 my CommonJS app crashes on Windows when I'm calling the `initialize` method from the `express-openapi` package:

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:372:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
    at defaultResolve (node:internal/modules/esm/resolve:1200:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1043:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
```

For Windows, the issue can be solved by changing in [openapi-framework/index.ts, line 238](https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-framework/index.ts#L238)

from
```typescript
const imported = await import(fsRoutesItem.path);
```
to 
```typescript
const imported = await import(`file:///${fsRoutesItem.path}`);
```
Of course, this is just a first dirty hack and not tested on other platforms than Windows. Can someone check this and provide a fixed version 12.0.1, please?

**Comment by jsdevel** [comment]
@robertkiel can you help here?

**Comment by robertkiel** [comment]
> @robertkiel can you help here?

Haven't tested the change on Windows yet ... The CommonJS script / ES module loader of Node.js seems to require some special treatment for Windows.

Will try on Windows tomorrow.

**Comment by renkei** [comment]
Any update on this?

**Comment by jsdevel** [comment]
@robertkiel would be great if you could provide some leadership/help here.

**Comment by robertkiel** [comment]
> @robertkiel would be great if you could provide some leadership/help here.

Sorry for the late reply. Have been busy with a different issue - also related ESM migrations which brought some insights

Need to create a Windows-based test setup first but it looks like most prefixing with `file:///` can work for many platforms.

**Comment by jsdevel** [comment]
@renkei can you try now with 12.0.1?  @robertkiel just pushed up a fix.

**Comment by renkei** [comment]
Thanks! It works on Windows again.

**Comment by jsdevel** [comment]
thanks for stepping in @robertkiel !!!
