### ISSUE TITLE
Where are breaking changes documented?

### ISSUE THREAD

**Issue by XuluWarrior** [kogosoftwarellc/open-api#814]
As #813 noted, v12 contained breaking change (`initialize` became async)

I agree that the version bump is adequate notice that a breaking change has taken place.  However, without @jaredhan418 getting there before me and creating #813, I would have had to go through the 1600 line change set to find out what had changed.

That is unless there is somewhere else I should have looked first?

**Comment by jsdevel** [comment]
@XuluWarrior if you have a way to automate a changelog, i'm all for adding it.

**Comment by renkei** [comment]
I'm also asking me if it is a good idea to provide the npm package express-openapi with version 12 with a CHANGELOG.md inside the package that stops at version 6.0.0 from 2019... For versions > 6.0.0 a link to this githib repo with a short explanation would be possibly helpful.

**Comment by jsdevel** [comment]
it was too much work to keep up to date manually.  if anyone would like to take a stab at automating it i'm all ears, but in general the git log is your friend.

**Comment by XuluWarrior** [comment]
Apologies for being slow replying to your questions.  If it's still timely here are my thoughts.

Firstly, I don't think anybody is demanding a comprehensive changelist.  I think important changes and specifically breaking ones are what's of concern.

I disagree with the statement that the git log is our friend in this recent breaking change as the log message gave no indication that there was any meaningful change in behaviour.  It was only by looking at the significant git diff that the nature of the breaking change became clear.
I don't think it's reasonable to expect consumers of a library to make their was through all git diffs to work out what has changed.

One suggestion I have is to make use of GitHub releases.  If you made one for each npm release then that would give a discoverable location to add important comments.  Even if it only mentioned breaking changes that would be very helpful.

As for automation, at my company we use [release-it](https://github.com/release-it/release-it)
I wasn't involved in choosing it, so can't give any comparison to other solutions.  But `release-it` will automate the process of updating package.lock files, publishing to npm and creating a GitHub release with a list of the PR's it contains.
I don't know how well it deals with monorepos like this one.

I hope the above is of some use.  I fully appreciate that maintaining an open source library is hard work and it's a lot easier to make suggestions about how things could be better than actually doing it

**Comment by jsdevel** [comment]
@XuluWarrior like i said, if you'd like to open a PR to automate the process feel free.  i'm an open source maintainer with limited time.  please don't expect perfection from me.  it takes enough of my time to review PRs and ensure devs are following the process accurately enough to ensure tests are passing etc.
